import {
  CLOUDFLARE_ASSETS_BINDING,
  CLOUDFLARE_OUTPUT_PACKAGE_FILE,
  CLOUDFLARE_PUBLIC_ASSETS_DIRECTORY,
  CLOUDFLARE_REQUIRED_COMPATIBILITY_FLAGS,
  CLOUDFLARE_RUNTIME_TYPE,
  CLOUDFLARE_WORKER_BUNDLE_DIRECTORY,
  CLOUDFLARE_WORKER_BUNDLE_FORMAT,
  CLOUDFLARE_WORKER_ENTRY,
  CLOUDFLARE_WORKER_MANIFEST,
  CLOUDFLARE_WRANGLER_CONFIG_FILE,
} from '../cloudflare-output-contract';

export { CLOUDFLARE_RUNTIME_TYPE, CLOUDFLARE_WORKER_BUNDLE_FORMAT };

export const WORKER_ENTRY = CLOUDFLARE_WORKER_ENTRY;
export const WORKER_MANIFEST = CLOUDFLARE_WORKER_MANIFEST;
export const WRANGLER_CONFIG_FILE = CLOUDFLARE_WRANGLER_CONFIG_FILE;
export const OUTPUT_PACKAGE_FILE = CLOUDFLARE_OUTPUT_PACKAGE_FILE;
export const ASSETS_BINDING = CLOUDFLARE_ASSETS_BINDING;
export const ROUTE_SPEC_FILE = 'route.json';
export const ROUTE_SPEC_OUTPUT = `server/${ROUTE_SPEC_FILE}`;
export const LOADABLE_STATS_FILE = 'loadable-stats.json';
export const ROUTE_MANIFEST_FILE = 'routes-manifest.json';
export const PUBLIC_ASSETS_DIRECTORY = CLOUDFLARE_PUBLIC_ASSETS_DIRECTORY;
export const WORKER_BUNDLE_DIRECTORY = CLOUDFLARE_WORKER_BUNDLE_DIRECTORY;
export const SERVER_BUNDLE_DIRECTORY = 'bundles';
export const SERVER_OUTPUT_DIRECTORY = 'server';
export const DEFAULT_SERVER_ONLY_PUBLIC_ASSET_EXCLUDES = [
  'api',
  'shared',
] as const;
export const BFF_EFFECT_WORKER_ENTRY = `${WORKER_BUNDLE_DIRECTORY}/__modern_bff_effect.js`;
export const BFF_EFFECT_WORKER_DISPATCHER_EXPORT =
  '__modern_create_effect_bff_dispatcher';
export const EFFECT_BFF_CLOUDFLARE_IMPORT_GUIDANCE =
  'Ensure the Effect API entry exists at api/index.ts or bff.effect.entry, and import Cloudflare edge handlers from @modern-js/plugin-bff/effect-edge instead of lambda/Hono server helpers.';
export const DEFAULT_COMPATIBILITY_DATE = '2026-06-02';
export const COMPATIBILITY_DATE_PATTERN = /^\d{4}-\d{2}-\d{2}$/u;
export const REQUIRED_COMPATIBILITY_FLAGS =
  CLOUDFLARE_REQUIRED_COMPATIBILITY_FLAGS;
export const RESERVED_ARTIFACT_DESTINATION_FILES = new Set([
  WRANGLER_CONFIG_FILE,
  OUTPUT_PACKAGE_FILE,
]);
export const RESERVED_ARTIFACT_DESTINATION_DIRECTORIES = new Set([
  PUBLIC_ASSETS_DIRECTORY,
  SERVER_OUTPUT_DIRECTORY,
  WORKER_BUNDLE_DIRECTORY,
]);
