import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { writeRouteMetadataManifest } from '../../src/cli/artifacts';
import { renderRouteMetadataManifest } from '../../src/cli/routeMetadata';

const routeMeta = (id: string) =>
  `export const routeMeta = { id: '${id}', namespace: 'shop' } as const;\n`;

const EXPECTED_MANIFEST = `// @generated by @modern-js/plugin-tanstack from route.meta.ts files. Run routes-generate; do not edit.
import { routeMeta as route0 } from './[lang]/about/route.meta';
import { routeMeta as route1 } from './[lang]/route.meta';
import { routeMeta as route2 } from './[lang]/stores/[id]/route.meta';

export const ultramodernRouteNamespace = route0.namespace;
export const ultramodernRouteMetadata = [route0, route1, route2] as const;
export const ultramodernLocalisedUrls = Object.fromEntries(
  ultramodernRouteMetadata
    .filter((route) => route.canonicalPath !== '/')
    .map((route) => [route.canonicalPath, route.localisedPaths]),
);
export const ultramodernPublicRoutes = ultramodernRouteMetadata
  .filter((route) => route.public && route.indexable)
  .map((route) => ({
    canonicalPath: route.canonicalPath,
    descriptionKey: route.descriptionKey,
    id: route.id,
    localisedPaths: route.localisedPaths,
    namespace: route.namespace,
    ownerAppId: route.ownerAppId,
    titleKey: route.titleKey,
    ...('jsonLd' in route ? { jsonLd: route.jsonLd } : {}),
  }));
export const ultramodernRouteConfig = {
  authoring: 'colocated-route-meta',
  generatedManifest: true,
  localisedUrls: ultramodernLocalisedUrls,
  namespace: ultramodernRouteNamespace,
  publicRoutes: ultramodernPublicRoutes,
  routes: ultramodernRouteMetadata,
  source: 'route-owned',
} as const;
`;

describe('route metadata manifest', () => {
  let appDirectory: string;
  let routesDirectory: string;
  const write = (relativePath: string, content: string) => {
    const file = path.join(routesDirectory, relativePath);
    fs.mkdirSync(path.dirname(file), { recursive: true });
    fs.writeFileSync(file, content);
  };

  beforeEach(() => {
    appDirectory = fs.mkdtempSync(path.join(os.tmpdir(), 'route-metadata-'));
    routesDirectory = path.join(appDirectory, 'src', 'routes');
  });

  afterEach(() => {
    fs.rmSync(appDirectory, { recursive: true, force: true });
  });

  it('writes a byte-stable, formatted manifest from route.meta.ts files', async () => {
    write('[lang]/stores/[id]/route.meta.ts', routeMeta('store'));
    write('[lang]/route.meta.ts', routeMeta('home'));
    write('[lang]/about/route.meta.ts', routeMeta('about'));
    write('[lang]/about/page.tsx', 'export default () => null;\n');
    // Linked metadata belongs to another tree; following it would make the
    // manifest depend on where the link points.
    fs.mkdirSync(path.join(routesDirectory, '[lang]/linked-file'));
    fs.symlinkSync(
      path.join(routesDirectory, '[lang]/route.meta.ts'),
      path.join(routesDirectory, '[lang]/linked-file/route.meta.ts'),
    );
    fs.symlinkSync(
      path.join(routesDirectory, '[lang]/about'),
      path.join(routesDirectory, '[lang]/linked'),
    );
    const manifestPath = path.join(
      routesDirectory,
      'ultramodern-route-metadata.ts',
    );

    await writeRouteMetadataManifest({ appDirectory });
    expect(fs.readFileSync(manifestPath, 'utf8')).toBe(EXPECTED_MANIFEST);

    const writtenAt = fs.statSync(manifestPath).mtimeMs;
    await new Promise(resolve => setTimeout(resolve, 20));
    await writeRouteMetadataManifest({ appDirectory });
    expect(fs.readFileSync(manifestPath, 'utf8')).toBe(EXPECTED_MANIFEST);
    expect(fs.statSync(manifestPath).mtimeMs).toBe(writtenAt);
  });

  it('drops deleted route metadata from an existing manifest', async () => {
    write('[lang]/route.meta.ts', routeMeta('home'));
    write('[lang]/gone/route.meta.ts', routeMeta('gone'));
    await writeRouteMetadataManifest({ appDirectory });
    fs.rmSync(path.join(routesDirectory, '[lang]/gone'), { recursive: true });

    await writeRouteMetadataManifest({ appDirectory });

    const manifest = fs.readFileSync(
      path.join(routesDirectory, 'ultramodern-route-metadata.ts'),
      'utf8',
    );
    expect(manifest).not.toContain('gone');
    expect(manifest).toContain(
      "import { routeMeta as route0 } from './[lang]/route.meta';\n\n",
    );
  });

  it('names the fix once the last route metadata is deleted', async () => {
    write('[lang]/route.meta.ts', routeMeta('home'));
    await writeRouteMetadataManifest({ appDirectory });
    const manifestPath = path.join(
      routesDirectory,
      'ultramodern-route-metadata.ts',
    );
    const manifest = fs.readFileSync(manifestPath, 'utf8');
    fs.rmSync(path.join(routesDirectory, '[lang]/route.meta.ts'));

    await expect(writeRouteMetadataManifest({ appDirectory })).rejects.toThrow(
      /none remain below .*Restore at least one route\.meta\.ts/u,
    );
    expect(fs.readFileSync(manifestPath, 'utf8')).toBe(manifest);
  });

  it('keeps an authored file at the manifest path', async () => {
    write('ultramodern-route-metadata.ts', 'export const authored = true;\n');

    await writeRouteMetadataManifest({ appDirectory });

    expect(
      fs.readFileSync(
        path.join(routesDirectory, 'ultramodern-route-metadata.ts'),
        'utf8',
      ),
    ).toBe('export const authored = true;\n');
  });

  it('writes nothing for an app without route metadata', async () => {
    await writeRouteMetadataManifest({ appDirectory });
    write('[lang]/page.tsx', 'export default () => null;\n');
    await writeRouteMetadataManifest({ appDirectory });

    expect(fs.readdirSync(routesDirectory)).toEqual(['[lang]']);
  });

  it('renders independently of input order and separators', () => {
    expect(
      renderRouteMetadataManifest([
        '[lang]\\stores\\[id]\\route.meta.ts',
        '[lang]/route.meta.ts',
        '[lang]/about/route.meta.ts',
      ]),
    ).toBe(EXPECTED_MANIFEST);
  });

  it('breaks the route list one binding per line past the print width', () => {
    const manifest = renderRouteMetadataManifest(
      Array.from({ length: 12 }, (_, index) => `r${index}/route.meta.ts`),
    );

    expect(manifest).toContain(
      `export const ultramodernRouteMetadata = [\n${Array.from(
        { length: 12 },
        (_, index) => `  route${index},\n`,
      ).join('')}] as const;\n`,
    );
  });
});
