// @effect-diagnostics asyncFunction:off nodeBuiltinImport:off strictBooleanExpressions:off processEnv:off processEnvInEffect:off

import path from 'node:path';
import type { AppToolsContext } from '@modern-js/app-tools';
import type { NestedRouteForCli, PageRoute } from '@modern-js/types';
import { fs } from '@modern-js/utils';

import {
  collectCanonicalRoutesForEntry,
  generateTanstackRouterTypesSourceForEntry,
} from './tanstackTypes';

const DEFAULT_GENERATED_DIR_NAME = 'modern-tanstack';

async function writeFileIfChanged(filePath: string, content: string) {
  try {
    const previous = (await fs.pathExists(filePath))
      ? await fs.readFile(filePath, 'utf-8')
      : null;
    if (previous === content) {
      return;
    }
  } catch {
    // Fall through and rewrite the generated file.
  }

  await fs.outputFile(filePath, content, 'utf-8');
}

function createRegisterDtsContent(opts: {
  entries: string[];
  runtimeModule: string;
  canonicalRoutes?: Record<string, string> | null;
  i18nRuntimeModule?: string;
}) {
  const importStatements = opts.entries
    .map(
      (entryName, index) =>
        `import type { router as router${index} } from './${entryName}/router.gen';`,
    )
    .join('\n');
  const routerUnionType = opts.entries
    .map((_, index) => `typeof router${index}`)
    .join(' | ');

  const canonicalEntries = Object.entries(opts.canonicalRoutes ?? {});
  const canonicalRoutesAugmentation =
    canonicalEntries.length > 0
      ? `
declare module '${opts.i18nRuntimeModule || '@modern-js/plugin-i18n/runtime'}' {
  interface UltramodernCanonicalRoutes {
${canonicalEntries
  .map(([routePath, paramsType]) => `    '${routePath}': ${paramsType};`)
  .join('\n')}
  }
}
`
      : '';

  return `// This file is auto-generated by Modern.js. Do not edit manually.

${importStatements}

declare module '${opts.runtimeModule}' {
  interface Register {
    router: ${routerUnionType};
  }
}
${canonicalRoutesAugmentation}`;
}

export async function writeTanstackRegisterFile(opts: {
  entries: string[];
  generatedDirName?: string;
  runtimeModule?: string;
  srcDirectory: string;
  canonicalRoutes?: Record<string, string> | null;
  i18nRuntimeModule?: string;
}) {
  const {
    entries,
    generatedDirName = DEFAULT_GENERATED_DIR_NAME,
    runtimeModule = '@modern-js/plugin-tanstack/runtime',
    srcDirectory,
    canonicalRoutes,
    i18nRuntimeModule,
  } = opts;

  if (entries.length === 0) {
    return;
  }

  const registerDtsPath = path.join(
    srcDirectory,
    generatedDirName,
    'register.gen.d.ts',
  );

  await writeFileIfChanged(
    registerDtsPath,
    createRegisterDtsContent({
      entries,
      runtimeModule,
      canonicalRoutes,
      i18nRuntimeModule,
    }),
  );
}

export async function writeTanstackRouterTypesForEntries(opts: {
  appContext: AppToolsContext;
  generatedDirName?: string;
  routesByEntry: Record<string, (NestedRouteForCli | PageRoute)[]>;
  /**
   * Whether `@modern-js/plugin-i18n` is actually installed in the app. The
   * `register.gen.d.ts` augmentation of '@modern-js/plugin-i18n/runtime' is
   * only emitted when this is true — otherwise apps with a hand-rolled
   * `/:lang/` param would fail typechecking on an unresolvable module.
   */
  i18nPluginInstalled?: boolean;
}) {
  const {
    appContext,
    generatedDirName = DEFAULT_GENERATED_DIR_NAME,
    routesByEntry,
    i18nPluginInstalled = false,
  } = opts;

  const entryNames = Object.keys(routesByEntry);

  await Promise.all(
    entryNames.map(async entryName => {
      const { routerGenTs } = await generateTanstackRouterTypesSourceForEntry({
        appContext,
        entryName,
        generatedDirName,
        routes: routesByEntry[entryName],
      });

      await writeFileIfChanged(
        path.join(
          appContext.srcDirectory,
          generatedDirName,
          entryName,
          'router.gen.ts',
        ),
        routerGenTs,
      );
    }),
  );

  const mainEntryName = appContext.entrypoints?.find(
    entrypoint => entrypoint.isMainEntry,
  )?.entryName;
  const registerEntries = entryNames.sort((a, b) => {
    if (mainEntryName && a === mainEntryName) {
      return -1;
    }

    if (mainEntryName && b === mainEntryName) {
      return 1;
    }

    return a.localeCompare(b);
  });

  // Merge the canonical (language-agnostic) route maps of every entry so the
  // typed i18n Link covers all routes the app can navigate to. Only relevant
  // when plugin-i18n is actually installed — without it the emitted module
  // augmentation would reference an unresolvable module.
  let canonicalRoutes: Record<string, string> | null = null;
  if (i18nPluginInstalled) {
    for (const entryName of registerEntries) {
      const entryCanonicalRoutes = collectCanonicalRoutesForEntry(
        routesByEntry[entryName],
        { localeParamHeuristic: true },
      );
      if (entryCanonicalRoutes) {
        canonicalRoutes = {
          ...entryCanonicalRoutes,
          ...(canonicalRoutes ?? {}),
        };
      }
    }
  }

  await writeTanstackRegisterFile({
    entries: registerEntries,
    generatedDirName,
    srcDirectory: appContext.srcDirectory,
    canonicalRoutes,
  });
}

/**
 * Headless regeneration of `router.gen.ts` / `register.gen.d.ts` for a generated
 * app, without running a full dev/build. Drives the app-tools analyze `onPrepare`
 * (which fires `generateEntryCode`) and returns before any bundling — the app's
 * own registered plugin-tanstack writes the artifacts via its `generateEntryCode`
 * subscriber. Reuses the exact hook dev/build use, so there is no scanning drift.
 */
export async function generateTanstackRouteArtifacts(opts: {
  appDirectory: string;
  version?: string;
}): Promise<void> {
  const [{ createRunOptions }, { cli }, utils] = await Promise.all([
    import('@modern-js/app-tools/cli/run'),
    import('@modern-js/plugin/cli'),
    import('@modern-js/utils'),
  ]);
  // Load-bearing, not decoration: app-tools' analyze.onPrepare only fires
  // generateEntryCode (the hook that writes the route artifacts) when
  // checkIsBuildCommands() is true, and getCommand() resolves the command
  // from MODERN_ARGV before process.argv — cli.init's `command` option does
  // not feed that check.
  process.env.MODERN_ARGV = 'node modern build';
  process.env.NODE_ENV = process.env.NODE_ENV || 'production';

  // Resolve the app's Modern.js config file ourselves and pass it as an
  // absolute base path. `createRunOptions` otherwise defaults its config lookup
  // to `process.cwd()` (not `cwd`/appDirectory), so headless invocations that
  // run from a different directory than the app — e.g. the create CLI spawning
  // this from the workspace root — find no config, and `findExists` returns
  // `false`. That `false` then flows into `cli.init` -> `getConfigFilePath` ->
  // `path.isAbsolute(false)`, throwing the opaque
  // `The "path" argument must be of type string. Received type boolean (false)`.
  // Passing an absolute base is resolution-based: cwd no longer matters, and the
  // downstream `getConfigFile` still appends the correct extension.
  const { findExists, CONFIG_FILE_EXTENSIONS } = utils as {
    findExists: (paths: string[]) => string | false;
    CONFIG_FILE_EXTENSIONS: string[];
  };
  const configFileBase = path.resolve(opts.appDirectory, 'modern.config');
  const resolvedConfigFile = findExists(
    CONFIG_FILE_EXTENSIONS.map(extension => `${configFileBase}${extension}`),
  );
  if (!resolvedConfigFile) {
    throw new Error(
      `[plugin-tanstack] Unable to locate a Modern.js config file (modern.config.{${CONFIG_FILE_EXTENSIONS.map(
        extension => extension.slice(1),
      ).join(',')}}) in ${opts.appDirectory}. ` +
        'TanStack route generation requires the app config to resolve its plugins.',
    );
  }

  const runOptions = await createRunOptions({
    cwd: opts.appDirectory,
    configFile: configFileBase,
    version:
      opts.version || process.env.MODERN_JS_VERSION || '0.0.0-routes-generate',
    internalPlugins: (utils as { INTERNAL_RUNTIME_PLUGINS: unknown })
      .INTERNAL_RUNTIME_PLUGINS as never,
  });
  await cli.init({ ...runOptions, command: 'build' });
}
