// @effect-diagnostics asyncFunction:off nodeBuiltinImport:off strictBooleanExpressions:off
import path from 'node:path';
import type {
  AppNormalizedConfig,
  AppTools,
  AppToolsContext,
  CliPlugin,
} from '@modern-js/app-tools';
import type { CLIPluginAPI } from '@modern-js/plugin';
import type {
  Entrypoint,
  NestedRouteForCli,
  PageRoute,
  ServerRoute,
} from '@modern-js/types';
import {
  filterRoutesForServer,
  fs,
  NESTED_ROUTE_SPEC_FILE,
} from '@modern-js/utils';
import {
  createTanstackRsbuildRouteSplittingProfile,
  type TanstackRouteCodeSplittingOption,
} from './routeSplitting';
import {
  collectCanonicalRoutesForEntry,
  generateTanstackRouterTypesSourceForEntry,
} from './tanstackTypes';

export type {
  TanstackRouteCodeSplittingOption,
  TanstackRsbuildRouteSplittingProfile,
} from './routeSplitting';
export {
  createTanstackRsbuildRouteSplittingProfile,
  resolveTanstackRouteCodeSplittingEnabled,
} from './routeSplitting';
export {
  type CollectCanonicalRoutesOptions,
  collectCanonicalRoutesForEntry,
  generateTanstackRouterTypesSourceForEntry,
} from './tanstackTypes';

const DEFAULT_ROUTES_DIR = 'routes';
const DEFAULT_GENERATED_DIR_NAME = 'modern-tanstack';
const ENTRYPOINTS_KEY = '@modern-js/plugin-tanstack';

export type TanstackRouterPluginOptions = {
  routesDir?: string;
  generatedDirName?: string;
  routeCodeSplitting?: TanstackRouteCodeSplittingOption;
};

type RuntimeRouterCliHelpers = {
  getEntrypointRoutesDir: (entrypoint: Entrypoint) => string | null;
  getEntrypointRoutesOwner: (entrypoint: Entrypoint) => string | null;
  handleFileChange: (
    api: CLIPluginAPI<AppTools>,
    event: unknown,
    options?: {
      includeEntry?: (entrypoint: Entrypoint) => boolean;
      regenerate?: (params: {
        api: CLIPluginAPI<AppTools>;
        appContext: ReturnType<CLIPluginAPI<AppTools>['getAppContext']>;
        resolvedConfig: AppNormalizedConfig;
        entrypoints: Entrypoint[];
      }) => Promise<void>;
      entrypointsKey?: string;
    },
  ) => Promise<void>;
  handleGeneratorEntryCode: (
    api: CLIPluginAPI<AppTools>,
    entrypoints: Entrypoint[],
    options?: {
      entrypointsKey?: string;
    },
  ) => Promise<Record<string, (NestedRouteForCli | PageRoute)[]>>;
  handleModifyEntrypoints: (
    entrypoints: Entrypoint[],
    routesDir?: string,
    options?: {
      routesOwner?: string;
    },
  ) => Promise<Entrypoint[]>;
  isRouteEntry: (dir: string, routesDir?: string) => string | false;
  updateNestedRoutesSpec: (
    specPath: string,
    nextRoutes: Record<string, unknown>,
  ) => Promise<void>;
};

let runtimeRouterCli: RuntimeRouterCliHelpers | undefined;

function getRuntimeRouterCli(): RuntimeRouterCliHelpers {
  if (runtimeRouterCli) {
    return runtimeRouterCli;
  }

  const cli =
    require('@modern-js/runtime/cli') as Partial<RuntimeRouterCliHelpers>;
  if (
    cli.handleGeneratorEntryCode &&
    cli.getEntrypointRoutesDir &&
    cli.getEntrypointRoutesOwner &&
    cli.updateNestedRoutesSpec
  ) {
    runtimeRouterCli = cli as RuntimeRouterCliHelpers;
    return runtimeRouterCli;
  }

  throw new Error(
    '@modern-js/plugin-tanstack requires @modern-js/runtime/cli router helper exports.',
  );
}

async function writeFileIfChanged(filePath: string, content: string) {
  try {
    const previous = (await fs.pathExists(filePath))
      ? await fs.readFile(filePath, 'utf-8')
      : null;
    if (previous === content) {
      return;
    }
  } catch {
    // Fall through and rewrite the generated file.
  }

  await fs.outputFile(filePath, content, 'utf-8');
}

function createRegisterDtsContent(opts: {
  entries: string[];
  runtimeModule: string;
  canonicalRoutes?: Record<string, string> | null;
  i18nRuntimeModule?: string;
}) {
  const importStatements = opts.entries
    .map(
      (entryName, index) =>
        `import type { router as router${index} } from './${entryName}/router.gen';`,
    )
    .join('\n');
  const routerUnionType = opts.entries
    .map((_, index) => `typeof router${index}`)
    .join(' | ');

  const canonicalEntries = Object.entries(opts.canonicalRoutes ?? {});
  const canonicalRoutesAugmentation =
    canonicalEntries.length > 0
      ? `
declare module '${opts.i18nRuntimeModule || '@modern-js/plugin-i18n/runtime'}' {
  interface UltramodernCanonicalRoutes {
${canonicalEntries
  .map(([routePath, paramsType]) => `    '${routePath}': ${paramsType};`)
  .join('\n')}
  }
}
`
      : '';

  return `// This file is auto-generated by Modern.js. Do not edit manually.

${importStatements}

declare module '${opts.runtimeModule}' {
  interface Register {
    router: ${routerUnionType};
  }
}
${canonicalRoutesAugmentation}`;
}

export async function writeTanstackRegisterFile(opts: {
  entries: string[];
  generatedDirName?: string;
  runtimeModule?: string;
  srcDirectory: string;
  canonicalRoutes?: Record<string, string> | null;
  i18nRuntimeModule?: string;
}) {
  const {
    entries,
    generatedDirName = DEFAULT_GENERATED_DIR_NAME,
    runtimeModule = '@modern-js/plugin-tanstack/runtime',
    srcDirectory,
    canonicalRoutes,
    i18nRuntimeModule,
  } = opts;

  if (entries.length === 0) {
    return;
  }

  const registerDtsPath = path.join(
    srcDirectory,
    generatedDirName,
    'register.gen.d.ts',
  );

  await writeFileIfChanged(
    registerDtsPath,
    createRegisterDtsContent({
      entries,
      runtimeModule,
      canonicalRoutes,
      i18nRuntimeModule,
    }),
  );
}

export async function writeTanstackRouterTypesForEntries(opts: {
  appContext: AppToolsContext;
  generatedDirName?: string;
  routesByEntry: Record<string, (NestedRouteForCli | PageRoute)[]>;
  /**
   * Whether `@modern-js/plugin-i18n` is actually installed in the app. The
   * `register.gen.d.ts` augmentation of '@modern-js/plugin-i18n/runtime' is
   * only emitted when this is true — otherwise apps with a hand-rolled
   * `/:lang/` param would fail typechecking on an unresolvable module.
   */
  i18nPluginInstalled?: boolean;
}) {
  const {
    appContext,
    generatedDirName = DEFAULT_GENERATED_DIR_NAME,
    routesByEntry,
    i18nPluginInstalled = false,
  } = opts;

  const entryNames = Object.keys(routesByEntry);

  await Promise.all(
    entryNames.map(async entryName => {
      const { routerGenTs } = await generateTanstackRouterTypesSourceForEntry({
        appContext,
        entryName,
        generatedDirName,
        routes: routesByEntry[entryName],
      });

      await writeFileIfChanged(
        path.join(
          appContext.srcDirectory,
          generatedDirName,
          entryName,
          'router.gen.ts',
        ),
        routerGenTs,
      );
    }),
  );

  const mainEntryName = appContext.entrypoints?.find(
    entrypoint => entrypoint.isMainEntry,
  )?.entryName;
  const registerEntries = entryNames.sort((a, b) => {
    if (mainEntryName && a === mainEntryName) {
      return -1;
    }

    if (mainEntryName && b === mainEntryName) {
      return 1;
    }

    return a.localeCompare(b);
  });

  // Merge the canonical (language-agnostic) route maps of every entry so the
  // typed i18n Link covers all routes the app can navigate to. Only relevant
  // when plugin-i18n is actually installed — without it the emitted module
  // augmentation would reference an unresolvable module.
  let canonicalRoutes: Record<string, string> | null = null;
  if (i18nPluginInstalled) {
    for (const entryName of registerEntries) {
      const entryCanonicalRoutes = collectCanonicalRoutesForEntry(
        routesByEntry[entryName],
        { localeParamHeuristic: true },
      );
      if (entryCanonicalRoutes) {
        canonicalRoutes = {
          ...entryCanonicalRoutes,
          ...(canonicalRoutes ?? {}),
        };
      }
    }
  }

  await writeTanstackRegisterFile({
    entries: registerEntries,
    generatedDirName,
    srcDirectory: appContext.srcDirectory,
    canonicalRoutes,
  });
}

export function tanstackRouterPlugin(
  options: TanstackRouterPluginOptions = {},
): CliPlugin<AppTools> {
  const routesDir = options.routesDir || DEFAULT_ROUTES_DIR;
  const generatedDirName =
    options.generatedDirName || DEFAULT_GENERATED_DIR_NAME;
  const routeSplittingProfile =
    createTanstackRsbuildRouteSplittingProfile(options);

  return {
    name: '@modern-js/plugin-tanstack',
    required: ['@modern-js/runtime'],
    setup: api => {
      const nestedRoutesForServer: Record<string, unknown> = {};

      const isTanstackEntrypoint = (entrypoint: Entrypoint) => {
        const { getEntrypointRoutesDir } = getRuntimeRouterCli();
        return getEntrypointRoutesDir(entrypoint) === routesDir;
      };

      // Entrypoints claimed by another file-route convention — the built-in
      // pages/ or routes/ entries of @modern-js/runtime's router plugin, or
      // an entry tagged by a different routes-owner plugin. Their router
      // runtime plugin must be left untouched: redirecting it through our
      // wrapper would value-import the TanStack runtime into bundles that
      // never use it, and pushing a second `router` plugin can install two
      // routers for one entry.
      const isForeignRouteEntrypoint = (entrypoint: Entrypoint) => {
        const { getEntrypointRoutesDir, getEntrypointRoutesOwner } =
          getRuntimeRouterCli();
        if (getEntrypointRoutesOwner(entrypoint)) {
          // Owned by some routes-owner plugin. TanStack-owned entries were
          // already claimed by the isTanstackEntrypoint branch, so any owner
          // seen here is foreign.
          return true;
        }
        if (entrypoint.pageRoutesEntry) {
          return true;
        }
        return getEntrypointRoutesDir(entrypoint) !== null;
      };

      const isI18nPluginInstalled = () => {
        const { plugins } = api.getAppContext() as {
          plugins?: Array<{ name?: string }>;
        };
        return Boolean(
          plugins?.some(plugin => plugin?.name === '@modern-js/plugin-i18n'),
        );
      };

      api._internalRuntimePlugins(({ entrypoint, plugins }) => {
        const { metaName, serverRoutes } = api.getAppContext();
        const serverBase = serverRoutes
          .filter(
            (route: ServerRoute) => route.entryName === entrypoint.entryName,
          )
          .map(route => route.urlPath)
          .sort((a, b) => (a.length - b.length > 0 ? -1 : 1));

        if (isTanstackEntrypoint(entrypoint as Entrypoint)) {
          plugins.push({
            name: 'tanstackRouter',
            path: `@${metaName}/plugin-tanstack/runtime`,
            config: { serverBase },
          });

          return { entrypoint, plugins };
        }

        // Entries owned by the built-in router (classic routes/ or pages/
        // conventions) or by another routes-owner plugin keep their own
        // router runtime plugin untouched.
        if (isForeignRouteEntrypoint(entrypoint as Entrypoint)) {
          return { entrypoint, plugins };
        }

        // True custom entry without any file-route convention (`createRoutes`
        // apps, hand-rolled App entries, ...): having this plugin installed
        // is the explicit signal that the app routes through the
        // router-provider registry — no source sniffing of modern.runtime.ts.
        // Inject the framework-resolving router plugin of @modern-js/runtime
        // through our own runtime/router module, so the TanStack provider
        // registration is value-imported together with it and can never be
        // tree-shaken away from the entry.
        const routerWrapperPath = `@${metaName}/plugin-tanstack/runtime/router`;
        const existingRouterPlugin = plugins.find(
          plugin => plugin.name === 'router',
        );
        if (existingRouterPlugin) {
          existingRouterPlugin.path = routerWrapperPath;
        } else {
          plugins.push({
            name: 'router',
            path: routerWrapperPath,
            config: { serverBase },
          });
        }

        return { entrypoint, plugins };
      });

      api.checkEntryPoint(({ path: entryPath, entry }) => ({
        path: entryPath,
        entry:
          entry || getRuntimeRouterCli().isRouteEntry(entryPath, routesDir),
      }));

      api.config(() => ({
        ...routeSplittingProfile.defaultConfig,
        source: {
          include: [
            // TanStack Router and its runtime deps ship modern syntax and
            // must be down-leveled for the app's browser targets.
            /[\\/]node_modules[\\/]@tanstack[\\/]react-router[\\/]/,
            /[\\/]node_modules[\\/]@tanstack[\\/]router-core[\\/]/,
            /[\\/]node_modules[\\/]@tanstack[\\/]react-store[\\/]/,
            // This package's own dist runtime, too. `__dirname` is
            // dist/{cjs,esm-node}/cli (or src/cli in tests), so the package
            // dist root is two levels up. Resolution-based — no string
            // surgery: the old `.replace('cjs', 'esm')` corrupted workspace
            // paths containing 'cjs' and, under the ESM CLI condition, never
            // matched the dist/esm runtime that browsers actually bundle.
            path.resolve(__dirname, '..', '..'),
          ],
        },
      }));

      api.modifyEntrypoints(async ({ entrypoints }) => {
        const { handleModifyEntrypoints } = getRuntimeRouterCli();
        return {
          entrypoints: await handleModifyEntrypoints(entrypoints, routesDir, {
            routesOwner: ENTRYPOINTS_KEY,
          }),
        };
      });

      api.generateEntryCode(async ({ entrypoints }) => {
        const tanstackEntrypoints = entrypoints.filter(isTanstackEntrypoint);

        if (tanstackEntrypoints.length === 0) {
          return;
        }

        const { handleGeneratorEntryCode } = getRuntimeRouterCli();
        const routesByEntry = await handleGeneratorEntryCode(
          api,
          tanstackEntrypoints,
          {
            entrypointsKey: ENTRYPOINTS_KEY,
          },
        );

        await writeTanstackRouterTypesForEntries({
          appContext: api.getAppContext(),
          generatedDirName,
          routesByEntry,
          i18nPluginInstalled: isI18nPluginInstalled(),
        });
      });

      api.onFileChanged(async event => {
        const { handleFileChange } = getRuntimeRouterCli();
        await handleFileChange(api, event, {
          entrypointsKey: ENTRYPOINTS_KEY,
          includeEntry: entrypoint => {
            const { getEntrypointRoutesDir } = getRuntimeRouterCli();
            return getEntrypointRoutesDir(entrypoint) === routesDir;
          },
          regenerate: async ({ api, entrypoints }) => {
            const { handleGeneratorEntryCode } = getRuntimeRouterCli();
            const routesByEntry = await handleGeneratorEntryCode(
              api,
              entrypoints,
              {
                entrypointsKey: ENTRYPOINTS_KEY,
              },
            );

            await writeTanstackRouterTypesForEntries({
              appContext: api.getAppContext(),
              generatedDirName,
              routesByEntry,
              i18nPluginInstalled: isI18nPluginInstalled(),
            });
          },
        });
      });

      api.modifyFileSystemRoutes(async ({ entrypoint, routes }) => {
        if (isTanstackEntrypoint(entrypoint)) {
          nestedRoutesForServer[entrypoint.entryName] = filterRoutesForServer(
            routes as (NestedRouteForCli | PageRoute)[],
          );
        }

        return {
          entrypoint,
          routes,
        };
      });

      api.onBeforeGenerateRoutes(async ({ entrypoint, code }) => {
        if (isTanstackEntrypoint(entrypoint)) {
          const { distDirectory } = api.getAppContext();
          const nestedRoutesSpecPath = path.resolve(
            distDirectory,
            NESTED_ROUTE_SPEC_FILE,
          );
          const { updateNestedRoutesSpec } = getRuntimeRouterCli();
          await updateNestedRoutesSpec(
            nestedRoutesSpecPath,
            nestedRoutesForServer,
          );
        }

        return {
          entrypoint,
          code,
        };
      });
    },
  };
}

export default tanstackRouterPlugin;
