// @effect-diagnostics asyncFunction:off nodeBuiltinImport:off strictBooleanExpressions:off
import path from 'node:path';
import type {
  AppNormalizedConfig,
  AppTools,
  AppToolsContext,
  CliPlugin,
} from '@modern-js/app-tools';
import type { CLIPluginAPI } from '@modern-js/plugin';
import type {
  Entrypoint,
  NestedRouteForCli,
  PageRoute,
  ServerRoute,
} from '@modern-js/types';
import {
  filterRoutesForServer,
  fs,
  NESTED_ROUTE_SPEC_FILE,
} from '@modern-js/utils';
import {
  createTanstackRsbuildRouteSplittingProfile,
  type TanstackRouteCodeSplittingOption,
} from './routeSplitting';
import {
  collectCanonicalRoutesForEntry,
  generateTanstackRouterTypesSourceForEntry,
  isTanstackRouterFrameworkEnabled,
} from './tanstackTypes';

export type {
  TanstackRouteCodeSplittingOption,
  TanstackRsbuildRouteSplittingProfile,
} from './routeSplitting';
export {
  createTanstackRsbuildRouteSplittingProfile,
  isTanstackStartRouteModuleSource,
  resolveTanstackRouteCodeSplittingEnabled,
} from './routeSplitting';
export {
  collectCanonicalRoutesForEntry,
  generateTanstackRouterTypesSourceForEntry,
  isTanstackRouterFrameworkEnabled,
} from './tanstackTypes';

const DEFAULT_ROUTES_DIR = 'routes';
const DEFAULT_GENERATED_DIR_NAME = 'modern-tanstack';
const ENTRYPOINTS_KEY = '@modern-js/plugin-tanstack';

export type TanstackRouterPluginOptions = {
  routesDir?: string;
  generatedDirName?: string;
  routeCodeSplitting?: TanstackRouteCodeSplittingOption;
};

type RuntimeRouterCliHelpers = {
  getEntrypointRoutesDir: (entrypoint: Entrypoint) => string | null;
  handleFileChange: (
    api: CLIPluginAPI<AppTools>,
    event: unknown,
    options?: {
      includeEntry?: (entrypoint: Entrypoint) => boolean;
      regenerate?: (params: {
        api: CLIPluginAPI<AppTools>;
        appContext: ReturnType<CLIPluginAPI<AppTools>['getAppContext']>;
        resolvedConfig: AppNormalizedConfig;
        entrypoints: Entrypoint[];
      }) => Promise<void>;
      entrypointsKey?: string;
    },
  ) => Promise<void>;
  handleGeneratorEntryCode: (
    api: CLIPluginAPI<AppTools>,
    entrypoints: Entrypoint[],
    options?: {
      entrypointsKey?: string;
    },
  ) => Promise<Record<string, (NestedRouteForCli | PageRoute)[]>>;
  handleModifyEntrypoints: (
    entrypoints: Entrypoint[],
    routesDir?: string,
    options?: {
      routesOwner?: string;
    },
  ) => Promise<Entrypoint[]>;
  isRouteEntry: (dir: string, routesDir?: string) => string | false;
};

let runtimeRouterCli: RuntimeRouterCliHelpers | undefined;

function getRuntimeRouterCli(): RuntimeRouterCliHelpers {
  if (runtimeRouterCli) {
    return runtimeRouterCli;
  }

  const cli =
    require('@modern-js/runtime/cli') as Partial<RuntimeRouterCliHelpers>;
  if (cli.handleGeneratorEntryCode && cli.getEntrypointRoutesDir) {
    runtimeRouterCli = cli as RuntimeRouterCliHelpers;
    return runtimeRouterCli;
  }

  throw new Error(
    '@modern-js/plugin-tanstack requires @modern-js/runtime/cli router helper exports.',
  );
}

async function writeFileIfChanged(filePath: string, content: string) {
  try {
    const previous = (await fs.pathExists(filePath))
      ? await fs.readFile(filePath, 'utf-8')
      : null;
    if (previous === content) {
      return;
    }
  } catch {
    // Fall through and rewrite the generated file.
  }

  await fs.outputFile(filePath, content, 'utf-8');
}

function createRegisterDtsContent(opts: {
  entries: string[];
  runtimeModule: string;
  canonicalRoutes?: Record<string, string> | null;
  i18nRuntimeModule?: string;
}) {
  const importStatements = opts.entries
    .map(
      (entryName, index) =>
        `import type { router as router${index} } from './${entryName}/router.gen';`,
    )
    .join('\n');
  const routerUnionType = opts.entries
    .map((_, index) => `typeof router${index}`)
    .join(' | ');

  const canonicalEntries = Object.entries(opts.canonicalRoutes ?? {});
  const canonicalRoutesAugmentation =
    canonicalEntries.length > 0
      ? `
declare module '${opts.i18nRuntimeModule || '@modern-js/plugin-i18n/runtime'}' {
  interface UltramodernCanonicalRoutes {
${canonicalEntries
  .map(([routePath, paramsType]) => `    '${routePath}': ${paramsType};`)
  .join('\n')}
  }
}
`
      : '';

  return `// This file is auto-generated by Modern.js. Do not edit manually.

${importStatements}

declare module '${opts.runtimeModule}' {
  interface Register {
    router: ${routerUnionType};
  }
}
${canonicalRoutesAugmentation}`;
}

export async function writeTanstackRegisterFile(opts: {
  entries: string[];
  generatedDirName?: string;
  runtimeModule?: string;
  srcDirectory: string;
  canonicalRoutes?: Record<string, string> | null;
  i18nRuntimeModule?: string;
}) {
  const {
    entries,
    generatedDirName = DEFAULT_GENERATED_DIR_NAME,
    runtimeModule = '@modern-js/plugin-tanstack/runtime',
    srcDirectory,
    canonicalRoutes,
    i18nRuntimeModule,
  } = opts;

  if (entries.length === 0) {
    return;
  }

  const registerDtsPath = path.join(
    srcDirectory,
    generatedDirName,
    'register.gen.d.ts',
  );

  await writeFileIfChanged(
    registerDtsPath,
    createRegisterDtsContent({
      entries,
      runtimeModule,
      canonicalRoutes,
      i18nRuntimeModule,
    }),
  );
}

export async function writeTanstackRouterTypesForEntries(opts: {
  appContext: AppToolsContext;
  generatedDirName?: string;
  routesByEntry: Record<string, (NestedRouteForCli | PageRoute)[]>;
}) {
  const {
    appContext,
    generatedDirName = DEFAULT_GENERATED_DIR_NAME,
    routesByEntry,
  } = opts;

  const entryNames = Object.keys(routesByEntry);

  await Promise.all(
    entryNames.map(async entryName => {
      const { routerGenTs } = await generateTanstackRouterTypesSourceForEntry({
        appContext,
        entryName,
        generatedDirName,
        routes: routesByEntry[entryName],
      });

      await writeFileIfChanged(
        path.join(
          appContext.srcDirectory,
          generatedDirName,
          entryName,
          'router.gen.ts',
        ),
        routerGenTs,
      );
    }),
  );

  const mainEntryName = appContext.entrypoints?.find(
    entrypoint => entrypoint.isMainEntry,
  )?.entryName;
  const registerEntries = entryNames.sort((a, b) => {
    if (mainEntryName && a === mainEntryName) {
      return -1;
    }

    if (mainEntryName && b === mainEntryName) {
      return 1;
    }

    return a.localeCompare(b);
  });

  // Merge the canonical (language-agnostic) route maps of every entry so the
  // typed i18n Link covers all routes the app can navigate to.
  let canonicalRoutes: Record<string, string> | null = null;
  for (const entryName of registerEntries) {
    const entryCanonicalRoutes = collectCanonicalRoutesForEntry(
      routesByEntry[entryName],
    );
    if (entryCanonicalRoutes) {
      canonicalRoutes = { ...entryCanonicalRoutes, ...(canonicalRoutes ?? {}) };
    }
  }

  await writeTanstackRegisterFile({
    entries: registerEntries,
    generatedDirName,
    srcDirectory: appContext.srcDirectory,
    canonicalRoutes,
  });
}

export function tanstackRouterPlugin(
  options: TanstackRouterPluginOptions = {},
): CliPlugin<AppTools> {
  const routesDir = options.routesDir || DEFAULT_ROUTES_DIR;
  const generatedDirName =
    options.generatedDirName || DEFAULT_GENERATED_DIR_NAME;
  const routeSplittingProfile =
    createTanstackRsbuildRouteSplittingProfile(options);

  return {
    name: '@modern-js/plugin-tanstack',
    required: ['@modern-js/runtime'],
    setup: api => {
      const nestedRoutesForServer: Record<string, unknown> = {};

      const isTanstackEntrypoint = (entrypoint: Entrypoint) => {
        const { getEntrypointRoutesDir } = getRuntimeRouterCli();
        return getEntrypointRoutesDir(entrypoint) === routesDir;
      };

      api._internalRuntimePlugins(({ entrypoint, plugins }) => {
        if (!isTanstackEntrypoint(entrypoint as Entrypoint)) {
          return { entrypoint, plugins };
        }

        const { metaName, serverRoutes } = api.getAppContext();
        const serverBase = serverRoutes
          .filter(
            (route: ServerRoute) => route.entryName === entrypoint.entryName,
          )
          .map(route => route.urlPath)
          .sort((a, b) => (a.length - b.length > 0 ? -1 : 1));

        plugins.push({
          name: 'tanstackRouter',
          path: `@${metaName}/plugin-tanstack/runtime`,
          config: { serverBase },
        });

        return { entrypoint, plugins };
      });

      api.checkEntryPoint(({ path: entryPath, entry }) => ({
        path: entryPath,
        entry:
          entry || getRuntimeRouterCli().isRouteEntry(entryPath, routesDir),
      }));

      api.config(() => ({
        ...routeSplittingProfile.defaultConfig,
        source: {
          include: [
            /[\\/]node_modules[\\/]@tanstack[\\/]react-router[\\/]/,
            path.resolve(__dirname, '../runtime').replace('cjs', 'esm'),
          ],
        },
      }));

      api.modifyEntrypoints(async ({ entrypoints }) => {
        const { handleModifyEntrypoints } = getRuntimeRouterCli();
        return {
          entrypoints: await handleModifyEntrypoints(entrypoints, routesDir, {
            routesOwner: ENTRYPOINTS_KEY,
          }),
        };
      });

      api.generateEntryCode(async ({ entrypoints }) => {
        const tanstackEntrypoints = entrypoints.filter(isTanstackEntrypoint);

        if (tanstackEntrypoints.length === 0) {
          return;
        }

        const { handleGeneratorEntryCode } = getRuntimeRouterCli();
        const routesByEntry = await handleGeneratorEntryCode(
          api,
          tanstackEntrypoints,
          {
            entrypointsKey: ENTRYPOINTS_KEY,
          },
        );

        await writeTanstackRouterTypesForEntries({
          appContext: api.getAppContext(),
          generatedDirName,
          routesByEntry,
        });
      });

      api.onFileChanged(async event => {
        const { handleFileChange } = getRuntimeRouterCli();
        await handleFileChange(api, event, {
          entrypointsKey: ENTRYPOINTS_KEY,
          includeEntry: entrypoint => {
            const { getEntrypointRoutesDir } = getRuntimeRouterCli();
            return getEntrypointRoutesDir(entrypoint) === routesDir;
          },
          regenerate: async ({ api, entrypoints }) => {
            const { handleGeneratorEntryCode } = getRuntimeRouterCli();
            const routesByEntry = await handleGeneratorEntryCode(
              api,
              entrypoints,
              {
                entrypointsKey: ENTRYPOINTS_KEY,
              },
            );

            await writeTanstackRouterTypesForEntries({
              appContext: api.getAppContext(),
              generatedDirName,
              routesByEntry,
            });
          },
        });
      });

      api.modifyFileSystemRoutes(async ({ entrypoint, routes }) => {
        if (isTanstackEntrypoint(entrypoint)) {
          nestedRoutesForServer[entrypoint.entryName] = filterRoutesForServer(
            routes as (NestedRouteForCli | PageRoute)[],
          );
        }

        return {
          entrypoint,
          routes,
        };
      });

      api.onBeforeGenerateRoutes(async ({ entrypoint, code }) => {
        if (isTanstackEntrypoint(entrypoint)) {
          const { distDirectory } = api.getAppContext();
          const nestedRoutesSpecPath = path.resolve(
            distDirectory,
            NESTED_ROUTE_SPEC_FILE,
          );
          const existingNestedRoutes = (await fs.pathExists(
            nestedRoutesSpecPath,
          ))
            ? ((await fs.readJSON(nestedRoutesSpecPath)) as Record<
                string,
                unknown
              >)
            : {};

          await fs.outputJSON(nestedRoutesSpecPath, {
            ...existingNestedRoutes,
            ...nestedRoutesForServer,
          });
        }

        return {
          entrypoint,
          code,
        };
      });
    },
  };
}

export default tanstackRouterPlugin;
