// @effect-diagnostics asyncFunction:off nodeBuiltinImport:off
import { readdir } from 'node:fs/promises';
import path from 'node:path';

export const ROUTE_META_FILE_NAME = 'route.meta.ts';
export const ROUTE_METADATA_MANIFEST_FILE_NAME =
  'ultramodern-route-metadata.ts';

export const ROUTE_METADATA_MANIFEST_HEADER = `// @generated by @modern-js/plugin-tanstack from ${ROUTE_META_FILE_NAME} files. Run routes-generate; do not edit.`;

// The manifest is emitted formatted (oxfmt/Prettier style: print width 120,
// single quotes, trailing commas) and is generated output, so formatters
// ignore it like router.gen.ts; no formatter pass is needed to keep it stable.
const PRINT_WIDTH = 120;

const MANIFEST_BODY = `export const ultramodernLocalisedUrls = Object.fromEntries(
  ultramodernRouteMetadata
    .filter((route) => route.canonicalPath !== '/')
    .map((route) => [route.canonicalPath, route.localisedPaths]),
);
export const ultramodernPublicRoutes = ultramodernRouteMetadata
  .filter((route) => route.public && route.indexable)
  .map((route) => ({
    canonicalPath: route.canonicalPath,
    descriptionKey: route.descriptionKey,
    id: route.id,
    localisedPaths: route.localisedPaths,
    namespace: route.namespace,
    ownerAppId: route.ownerAppId,
    titleKey: route.titleKey,
    ...('jsonLd' in route ? { jsonLd: route.jsonLd } : {}),
  }));
export const ultramodernRouteConfig = {
  authoring: 'colocated-route-meta',
  generatedManifest: true,
  localisedUrls: ultramodernLocalisedUrls,
  namespace: ultramodernRouteNamespace,
  publicRoutes: ultramodernPublicRoutes,
  routes: ultramodernRouteMetadata,
  source: 'route-owned',
} as const;
`;

const compareCodeUnits = (left: string, right: string) =>
  left < right ? -1 : left > right ? 1 : 0;

const quoteSpecifier = (specifier: string) =>
  specifier.includes("'") ? JSON.stringify(specifier) : `'${specifier}'`;

/**
 * Renders the route metadata manifest for the `route.meta.ts` files of one
 * routes directory. Each path is relative to that directory (either separator).
 * Every `route.meta.ts` must export `routeMeta`; the manifest imports it
 * statically, so the metadata is never evaluated while generating. Returns
 * `null` when there are no route metadata files. Output depends only on the
 * set of paths, never on their order or on the file system.
 */
export function renderRouteMetadataManifest(
  routeMetaFiles: readonly string[],
): string | null {
  const specifiers = routeMetaFiles
    .map(file => `./${file.replaceAll('\\', '/').replace(/\.ts$/u, '')}`)
    .sort(compareCodeUnits);
  if (specifiers.length === 0) {
    return null;
  }
  const bindings = specifiers.map((_, index) => `route${index}`);
  const imports = specifiers.map(
    (specifier, index) =>
      `import { routeMeta as ${bindings[index]} } from ${quoteSpecifier(specifier)};`,
  );
  const inlineRoutes = `export const ultramodernRouteMetadata = [${bindings.join(', ')}] as const;`;
  const routes =
    inlineRoutes.length <= PRINT_WIDTH
      ? inlineRoutes
      : `export const ultramodernRouteMetadata = [\n${bindings
          .map(binding => `  ${binding},\n`)
          .join('')}] as const;`;

  return `${ROUTE_METADATA_MANIFEST_HEADER}
${imports.join('\n')}

export const ultramodernRouteNamespace = route0.namespace;
${routes}
${MANIFEST_BODY}`;
}

/**
 * Lists the `route.meta.ts` files below `routesDirectory`, relative to it.
 * Symbolic links are not followed: linked metadata belongs to the tree it
 * lives in. A missing directory has no route metadata.
 */
export async function findRouteMetaFiles(
  routesDirectory: string,
): Promise<string[]> {
  const files: string[] = [];
  const visit = async (relativeDirectory: string): Promise<void> => {
    const entries = await readdir(
      path.join(routesDirectory, relativeDirectory),
      { withFileTypes: true },
    );
    for (const entry of entries) {
      const relativePath = path.join(relativeDirectory, entry.name);
      if (entry.isDirectory()) {
        await visit(relativePath);
      } else if (entry.isFile() && entry.name === ROUTE_META_FILE_NAME) {
        files.push(relativePath);
      }
    }
  };
  try {
    await visit('');
  } catch (error) {
    const { code, path: missingPath } = error as NodeJS.ErrnoException;
    if (code === 'ENOENT' && missingPath === routesDirectory) {
      return [];
    }
    throw error;
  }
  return files;
}
