import {
  appHasApi,
  resolveApiPrefix,
  resolveApiProtocol,
  resolveApiStem,
} from './descriptors';
import { packageName } from './naming';
import type { WorkspaceApp } from './types';
import { NODE_VERSION } from './versions';

const zeropsNodeRuntime = `nodejs@${NODE_VERSION.split('.')[0]}`;

function quoteYamlString(value: string) {
  return `'${value.replace(/'/gu, "''")}'`;
}

function quoteShellValue(value: string) {
  return `'${value.replace(/'/gu, "'\\''")}'`;
}

function readinessPath(app: WorkspaceApp) {
  if (!appHasApi(app)) {
    return '/';
  }

  return `${resolveApiPrefix(app)}/${resolveApiStem(app)}/readiness`;
}

function hasHttpReadiness(app: WorkspaceApp) {
  return !appHasApi(app) || resolveApiProtocol(app) === 'rest';
}

function createZeropsService(scope: string, app: WorkspaceApp) {
  const runtimeDirectory = `.zerops/runtime/${app.id}`;
  const appPackageName = packageName(scope, app.packageSuffix);
  const commands = [
    'curl https://mise.run | sh',
    '~/.local/bin/mise install',
    '~/.local/bin/mise exec -- pnpm install --frozen-lockfile',
    `~/.local/bin/mise exec -- pnpm --filter ${quoteShellValue(appPackageName)} run build`,
    `~/.local/bin/mise exec -- pnpm run zerops:materialize -- --app ${quoteShellValue(app.id)} --package ${quoteShellValue(appPackageName)} --package-dir ${quoteShellValue(app.directory)}`,
    `cp ${quoteShellValue('topology/reference-topology.json')} ${quoteShellValue(`${runtimeDirectory}/topology.json`)}`,
    `cp ${quoteShellValue('topology/local-overlays/development.json')} ${quoteShellValue(`${runtimeDirectory}/local-overlay.json`)}`,
  ];

  return [
    `  - setup: ${quoteYamlString(app.id)}`,
    '    build:',
    `      base: ${quoteYamlString(zeropsNodeRuntime)}`,
    '      buildCommands:',
    '        - |',
    ...commands.map(command => `          ${command}`),
    '      deployFiles:',
    `        - ${quoteYamlString(runtimeDirectory)}`,
    '    deploy:',
    '      temporaryShutdown: false',
    ...(hasHttpReadiness(app)
      ? [
          '      readinessCheck:',
          '        httpGet:',
          `          port: ${app.port}`,
          `          path: ${quoteYamlString(readinessPath(app))}`,
          '        failureTimeout: 120',
          '        retryPeriod: 10',
        ]
      : []),
    '    run:',
    `      base: ${quoteYamlString(zeropsNodeRuntime)}`,
    '      ports:',
    `        - port: ${app.port}`,
    '          protocol: TCP',
    '          httpSupport: true',
    '      envVariables:',
    '        NODE_ENV: production',
    `        ${app.portEnv}: ${quoteYamlString(String(app.port))}`,
    `        ULTRAMODERN_ZEROPS_SERVICE: ${quoteYamlString(app.id)}`,
    `      start: cd ${quoteShellValue(runtimeDirectory)} && npm run serve`,
  ].join('\n');
}

export function createZeropsYaml(scope: string, apps: WorkspaceApp[]) {
  return [
    '# Generated by Modern.js UltraModern workspace tooling.',
    '# Zerops runs each full-stack MicroVertical as a package-owned Node service.',
    'zerops:',
    ...apps.map(app => createZeropsService(scope, app)),
  ].join('\n\n');
}
