import path from 'node:path';
import {
  BACKEND_FEDERATION_EFFECT_EXPOSE as BACKEND_EXPOSE,
  BACKEND_FEDERATION_MANIFEST_FILE as BACKEND_MANIFEST_FILE,
  BACKEND_FEDERATION_REMOTE_ENTRY_FILE as BACKEND_REMOTE_ENTRY_FILE,
  BACKEND_FEDERATION_CONTRACT_VERSION as CONTRACT_VERSION,
  formatBackendFederationValidationErrors,
  BACKEND_FEDERATION_NODE_ADAPTER_VERSION as NODE_ADAPTER_VERSION,
  validateBackendFederationManifest,
} from '@modern-js/utils/universal';
import { type BackendFederationApp, normalizeRelativePath } from './config';

const createRelativeImportSpecifier = (
  fromDirectory: string,
  toFile: string,
) => {
  const relativePath = normalizeRelativePath(
    path.relative(fromDirectory, toFile),
  );
  return relativePath.startsWith('.') ? relativePath : `./${relativePath}`;
};

export const createBackendRemoteEntrySource = (
  workspaceRoot: string,
  app: BackendFederationApp,
  effectApiPath: string,
  entryPath: string,
) => {
  const effectApiSpecifier = createRelativeImportSpecifier(
    path.dirname(entryPath),
    effectApiPath,
  );

  return `// Generated by Modern.js backend federation build.
const exposedModules = {
  ${JSON.stringify(BACKEND_EXPOSE)}: () =>
    import(new URL(${JSON.stringify(effectApiSpecifier)}, import.meta.url).href),
};

export const __modernjsBackendFederation = ${JSON.stringify(
    {
      buildVersion: app.buildVersion,
      expose: BACKEND_EXPOSE,
      name: app.backendName,
      packageName: app.packageName,
      remoteType: app.remoteType,
      source: normalizeRelativePath(
        path.relative(workspaceRoot, effectApiPath),
      ),
      version: app.version,
      ...(app.unitId ? { unitId: app.unitId } : {}),
      ...(app.sourceRevision ? { sourceRevision: app.sourceRevision } : {}),
    },
    null,
    2,
  )};

export function init() {}

export function get(id) {
  const load = exposedModules[id];
  if (!load) {
    throw new Error(\`Unexpected backend federation expose: \${id}\`);
  }

  return async () => load();
}

export default { get, init };
`;
};

export const createBackendManifest = (
  workspaceRoot: string,
  distDirectory: string,
  app: BackendFederationApp,
) => {
  const sourceModule = `${app.directory}/api/effect-api.ts`;
  const publicPath = `http://localhost:${app.port}/`;

  const manifest = {
    schemaVersion: 1,
    id: app.backendName,
    name: app.backendName,
    version: app.version,
    buildVersion: app.buildVersion,
    metaData: {
      name: app.backendName,
      type: 'backend',
      buildInfo: {
        buildVersion: app.buildVersion,
        buildName: app.packageName,
      },
      remoteEntry: {
        name: BACKEND_REMOTE_ENTRY_FILE,
        path: '',
        type: app.remoteType,
      },
      globalName: app.backendName,
      publicPath,
      ssrRemoteEntry: {
        name: BACKEND_REMOTE_ENTRY_FILE,
        path: '',
        type: app.remoteType,
      },
      ssrPublicPath: publicPath,
    },
    entry: {
      file: BACKEND_REMOTE_ENTRY_FILE,
      path: normalizeRelativePath(
        path.relative(
          workspaceRoot,
          path.join(distDirectory, BACKEND_REMOTE_ENTRY_FILE),
        ),
      ),
      type: app.remoteType,
      url: app.containerEntry,
    },
    exposes: [
      {
        id: `${app.backendName}:${BACKEND_EXPOSE}`,
        name: BACKEND_EXPOSE,
        path: '',
        assets: {
          js: {
            async: [],
            sync: [BACKEND_REMOTE_ENTRY_FILE],
          },
          css: {
            async: [],
            sync: [],
          },
        },
      },
    ],
    shared: [],
    backendFederation: {
      role: 'microvertical-server',
      name: app.backendName,
      runtimeFramework: 'effect',
      strictEffectApproach: true,
      contractVersion: CONTRACT_VERSION,
      nodeAdapterVersion: NODE_ADAPTER_VERSION,
      remoteType: app.remoteType,
      expose: BACKEND_EXPOSE,
      manifestUrl: app.manifestUrl,
      containerEntry: app.containerEntry,
      source: {
        module: sourceModule,
      },
      readinessPath: `${app.apiPrefix}/${app.apiStem}/readiness`,
      openapiPath: `${app.apiPrefix}/openapi.json`,
      ...(app.deliveryUnit ? { deliveryUnit: app.deliveryUnit } : {}),
      versionBoundary: {
        invariant: 'web-and-api-same-build',
        packageName: app.packageName,
        version: app.version,
        buildVersion: app.buildVersion,
        ...(app.uiManifestUrl ? { uiManifestUrl: app.uiManifestUrl } : {}),
        ...(app.deliveryUnit
          ? {
              deliveryUnit: {
                unitId: app.deliveryUnit.unitId,
                buildMarker: app.deliveryUnit.buildMarker,
                sourceRevision: app.deliveryUnit.sourceRevision,
              },
            }
          : {}),
      },
    },
  };

  const validation = validateBackendFederationManifest(manifest, {
    path: 'backendFederationManifest',
    requireEffectExpose: true,
    requireEffectRuntime: true,
    requireVersionFields: true,
  });

  if (!validation.ok) {
    throw new Error(
      `[backend-federation-build] Invalid backend federation manifest: ${formatBackendFederationValidationErrors(
        validation.errors,
      )}.`,
    );
  }

  return manifest;
};
