import path from 'node:path';
import {
  BACKEND_FEDERATION_EFFECT_EXPOSE as BACKEND_EXPOSE,
  BACKEND_FEDERATION_MANIFEST_FILE as BACKEND_MANIFEST_FILE,
  BACKEND_FEDERATION_REMOTE_ENTRY_FILE as BACKEND_REMOTE_ENTRY_FILE,
  BACKEND_FEDERATION_CONTRACT_VERSION as CONTRACT_VERSION,
  formatBackendFederationValidationErrors,
  BACKEND_FEDERATION_NODE_ADAPTER_VERSION as NODE_ADAPTER_VERSION,
  validateBackendFederationManifest,
} from '@modern-js/utils/universal';
import { build } from 'esbuild';
import { type BackendFederationApp, normalizeRelativePath } from './config';

const createRelativeImportSpecifier = (
  fromDirectory: string,
  toFile: string,
) => {
  const relativePath = normalizeRelativePath(
    path.relative(fromDirectory, toFile),
  );
  return relativePath.startsWith('.') ? relativePath : `./${relativePath}`;
};

const createPublicPath = (containerEntry: string, fallbackPort: number) => {
  try {
    return new URL('.', containerEntry).href;
  } catch {
    const slashIndex = containerEntry.lastIndexOf('/');
    if (slashIndex >= 0) {
      return containerEntry.slice(0, slashIndex + 1);
    }

    return `http://localhost:${fallbackPort}/`;
  }
};

export const createBackendRemoteEntrySource = async (
  workspaceRoot: string,
  app: BackendFederationApp,
  effectApiPath: string,
  entryPath: string,
) => {
  const effectApiSpecifier = createRelativeImportSpecifier(
    path.dirname(effectApiPath),
    effectApiPath,
  );
  const containerMetadata = {
    buildVersion: app.buildVersion,
    expose: BACKEND_EXPOSE,
    name: app.backendName,
    packageName: app.packageName,
    remoteType: app.remoteType,
    source: normalizeRelativePath(path.relative(workspaceRoot, effectApiPath)),
    version: app.version,
    ...(app.unitId ? { unitId: app.unitId } : {}),
    ...(app.sourceRevision ? { sourceRevision: app.sourceRevision } : {}),
  };
  const compatibility = {
    build: app.buildVersion,
    contractVersion: CONTRACT_VERSION,
    nodeAdapterVersion: NODE_ADAPTER_VERSION,
    packageName: app.packageName,
    ...(app.unitId ? { unitId: app.unitId } : {}),
    ...(app.sourceRevision ? { sourceRevision: app.sourceRevision } : {}),
  };
  const source = `// Generated by Modern.js backend federation build.
import * as exposedNamespace from ${JSON.stringify(effectApiSpecifier)};

const exposedModule = {
  ...exposedNamespace,
  backendFederationContract: {
    ...(exposedNamespace.backendFederationContract ?? {}),
    compatibility: {
      ...(exposedNamespace.backendFederationContract?.compatibility ?? {}),
      ...${JSON.stringify(compatibility)},
    },
    name: ${JSON.stringify(app.backendName)},
    role: 'microvertical-server',
    runtimeFramework: 'effect',
    strictEffectApproach: true,
  },
};
const exposedModules = {
  ${JSON.stringify(BACKEND_EXPOSE)}: () => Promise.resolve(exposedModule),
};
const __modernjsBackendFederation = ${JSON.stringify(containerMetadata)};

function init() {}

function get(id) {
  const load = exposedModules[id];
  if (!load) {
    throw new Error(\`Unexpected backend federation expose: \${id}\`);
  }

  return async () => load();
}

module.exports = { __modernjsBackendFederation, get, init };
`;
  const result = await build({
    absWorkingDir: path.dirname(effectApiPath),
    bundle: true,
    format: 'cjs',
    logLevel: 'silent',
    platform: 'node',
    stdin: {
      contents: source,
      loader: 'ts',
      resolveDir: path.dirname(effectApiPath),
      sourcefile: path.basename(entryPath),
    },
    target: 'node20',
    write: false,
  });
  const output = result.outputFiles[0];
  if (!output) {
    throw new Error(
      '[backend-federation-build] CommonJS backend federation container emitted no output.',
    );
  }
  return output.text;
};

export const createBackendManifest = (
  workspaceRoot: string,
  distDirectory: string,
  app: BackendFederationApp,
) => {
  const sourceModule = `${app.directory}/api/effect-api.ts`;
  const publicPath = createPublicPath(app.containerEntry, app.port);

  const manifest = {
    schemaVersion: 1,
    id: app.backendName,
    name: app.backendName,
    version: app.version,
    buildVersion: app.buildVersion,
    metaData: {
      name: app.backendName,
      type: 'backend',
      buildInfo: {
        buildVersion: app.buildVersion,
        buildName: app.packageName,
      },
      remoteEntry: {
        name: BACKEND_REMOTE_ENTRY_FILE,
        path: '',
        type: app.remoteType,
      },
      globalName: app.backendName,
      publicPath,
      ssrRemoteEntry: {
        name: BACKEND_REMOTE_ENTRY_FILE,
        path: '',
        type: app.remoteType,
      },
      ssrPublicPath: publicPath,
    },
    entry: {
      file: BACKEND_REMOTE_ENTRY_FILE,
      path: normalizeRelativePath(
        path.relative(
          workspaceRoot,
          path.join(distDirectory, BACKEND_REMOTE_ENTRY_FILE),
        ),
      ),
      type: app.remoteType,
      url: app.containerEntry,
    },
    exposes: [
      {
        id: `${app.backendName}:${BACKEND_EXPOSE}`,
        name: BACKEND_EXPOSE,
        path: '',
        assets: {
          js: {
            async: [],
            sync: [BACKEND_REMOTE_ENTRY_FILE],
          },
          css: {
            async: [],
            sync: [],
          },
        },
      },
    ],
    shared: [],
    backendFederation: {
      role: 'microvertical-server',
      appId: app.id,
      name: app.backendName,
      runtimeFramework: 'effect',
      strictEffectApproach: true,
      contractVersion: CONTRACT_VERSION,
      nodeAdapterVersion: NODE_ADAPTER_VERSION,
      remoteType: app.remoteType,
      expose: BACKEND_EXPOSE,
      manifestUrl: app.manifestUrl,
      containerEntry: app.containerEntry,
      source: {
        module: sourceModule,
      },
      readinessPath: `${app.apiPrefix}/${app.apiStem}/readiness`,
      openapiPath: `${app.apiPrefix}/openapi.json`,
      ...(app.deliveryUnit ? { deliveryUnit: app.deliveryUnit } : {}),
      versionBoundary: {
        invariant: 'web-and-api-same-build',
        packageName: app.packageName,
        version: app.version,
        buildVersion: app.buildVersion,
        ...(app.uiManifestUrl ? { uiManifestUrl: app.uiManifestUrl } : {}),
        ...(app.deliveryUnit
          ? {
              deliveryUnit: {
                unitId: app.deliveryUnit.unitId,
                buildMarker: app.deliveryUnit.buildMarker,
                sourceRevision: app.deliveryUnit.sourceRevision,
              },
            }
          : {}),
      },
    },
  };

  const validation = validateBackendFederationManifest(manifest, {
    path: 'backendFederationManifest',
    requireEffectExpose: true,
    requireEffectRuntime: true,
    requireVersionFields: true,
  });

  if (!validation.ok) {
    throw new Error(
      `[backend-federation-build] Invalid backend federation manifest: ${formatBackendFederationValidationErrors(
        validation.errors,
      )}.`,
    );
  }

  return manifest;
};
