// This file is auto-generated by Modern.js. Do not edit manually.

import {
  createMemoryHistory,
  createRootRouteWithContext,
  createRoute,
  createRouter,
  createRouteStaticData,
  type ModernRouterContext,
  modernLoaderToTanstack,
  modernTanstackRouterFastDefaults,
} from '@modern-js/plugin-tanstack/runtime';

import loader_0 from "../../string/routes/layout.loader";
import { loader as loader_1 } from "../../string/routes/page.data";
import component_0 from "../../string/routes/page";
import component_1 from "../../string/routes/blocker/page";
import { loader as loader_2, action as action_2 } from "../../string/routes/mutation/page.data";
import component_2 from "../../string/routes/mutation/page";
import { loader as loader_3 } from "../../string/routes/optional/[id$]/page.data";
import component_3 from "../../string/routes/optional/[id$]/page";
import { loader as loader_4 } from "../../string/routes/redirect/page.data";
import component_4 from "../../string/routes/redirect/page";
import { loader as loader_5 } from "../../string/routes/user/[id]/page.data";
import component_5 from "../../string/routes/user/[id]/page";
import component_6 from "../../string/routes/layout";

export const rootRoute = createRootRouteWithContext<ModernRouterContext>()({
  component: component_6,
  loader: modernLoaderToTanstack({ hasSplat: false }, loader_0),
  staticData: createRouteStaticData({
    modernRouteId: "string_layout",
    modernRouteLoader: loader_0,
  }),
});

const route_string_page = createRoute({
  getParentRoute: () => rootRoute,
  component: component_0,
  path: "/",
  loader: modernLoaderToTanstack({ hasSplat: false }, loader_1),
  staticData: createRouteStaticData({
    modernRouteId: "string_page",
    modernRouteLoader: loader_1,
  }),
});

const route_string_blocker_page = createRoute({
  getParentRoute: () => rootRoute,
  component: component_1,
  path: "blocker",
  staticData: createRouteStaticData({
    modernRouteId: "string_blocker/page",
  }),
});

const route_string_mutation_page = createRoute({
  getParentRoute: () => rootRoute,
  component: component_2,
  path: "mutation",
  loader: modernLoaderToTanstack({ hasSplat: false }, loader_2),
  staticData: createRouteStaticData({
    modernRouteId: "string_mutation/page",
    modernRouteLoader: loader_2,
    modernRouteAction: action_2,
  }),
});

const route_string_optional__id$__page = createRoute({
  getParentRoute: () => rootRoute,
  component: component_3,
  path: "optional/{-$id}",
  loader: modernLoaderToTanstack({ hasSplat: false }, loader_3),
  staticData: createRouteStaticData({
    modernRouteId: "string_optional/(id$)/page",
    modernRouteLoader: loader_3,
  }),
});

const route_string_redirect_page = createRoute({
  getParentRoute: () => rootRoute,
  component: component_4,
  path: "redirect",
  loader: modernLoaderToTanstack({ hasSplat: false }, loader_4),
  staticData: createRouteStaticData({
    modernRouteId: "string_redirect/page",
    modernRouteLoader: loader_4,
  }),
});

const route_string_user__id__page = createRoute({
  getParentRoute: () => rootRoute,
  component: component_5,
  path: "user/$id",
  loader: modernLoaderToTanstack({ hasSplat: false }, loader_5),
  staticData: createRouteStaticData({
    modernRouteId: "string_user/(id)/page",
    modernRouteLoader: loader_5,
  }),
});

export const routeTree = rootRoute.addChildren([route_string_page, route_string_blocker_page, route_string_mutation_page, route_string_optional__id$__page, route_string_redirect_page, route_string_user__id__page]);

export const router = createRouter({
  ...modernTanstackRouterFastDefaults,
  routeTree,
  history: createMemoryHistory({
    initialEntries: ['/'],
  }),
  context: {} as ModernRouterContext,
});
