import { commonFiles } from './common';

export const ModuleFiles = {
  ...commonFiles,
  ...{
  ".npmignore": ".DS_Store\n\n.pnp\n.pnp.js\n.env.local\n.env.*.local\n.history\n*.log*\n\nnode_modules/\n.yarn-integrity\n*.tsbuildinfo\n.eslintcache\n\ncoverage/\nrelease/\noutput/\noutput_resource/\ntests/\n\n.vscode/**/*\n!.vscode/settings.json\n!.vscode/extensions.json\n.idea/\n\nsrc/\n\nmodern.config.*\njest.config.js\n.eslintrc.js\n.eslintrc\ntsconfig.json\nCHANGELOG.md\n\n**/*/api/typings/auto-generated\n",
  "package.json": "{\n  \"name\": \"modern-npm-module\",\n  \"version\": \"0.1.0\",\n  \"types\": \"./dist/types/index.d.ts\",\n  \"main\": \"./dist/lib/index.js\",\n  \"module\": \"./dist/es/index.js\",\n  \"scripts\": {\n    \"prepare\": \"modern build && husky install\",\n    \"dev\": \"modern dev\",\n    \"build\": \"modern build\",\n    \"build:watch\": \"modern build -w\",\n    \"reset\": \"rimraf ./**/node_modules\",\n    \"lint\": \"modern lint\",\n    \"change\": \"modern change\",\n    \"bump\": \"modern bump\",\n    \"pre\": \"modern pre\",\n    \"change-status\": \"modern change-status\",\n    \"gen-release-note\": \"modern gen-release-note\",\n    \"release\": \"modern release\",\n    \"new\": \"modern new\",\n    \"upgrade\": \"modern upgrade\"\n  },\n  \"lint-staged\": {\n    \"*.{js,jsx,ts,tsx,mjs,cjs}\": [\n      \"node --max_old_space_size=8192 ./node_modules/eslint/bin/eslint.js --fix --color --cache --quiet\"\n    ]\n  },\n  \"eslintIgnore\": [\n    \"node_modules/\",\n    \"dist/\"\n  ],\n  \"dependencies\": {},\n  \"peerDependencies\": {},\n  \"devDependencies\": {\n    \"@modern-js/module-tools\": \"2.70.4\",\n    \"@modern-js/eslint-config\": \"2.70.4\",\n    \"@modern-js/tsconfig\":\"2.70.4\",\n    \"@modern-js-app/eslint-config\": \"2.70.4\",\n    \"@typescript/native-preview\": \"7.0.0-dev.20260516.1\",\n    \"@types/jest\": \"~29.2.4\",\n    \"@types/node\": \"~16.11.7\",\n    \"@types/react\": \"~18.0.26\",\n    \"rimraf\": \"~3.0.2\",\n    \"lint-staged\": \"~13.1.0\",\n    \"prettier\": \"~2.8.1\",\n    \"husky\": \"~8.0.1\"\n  },\n  \"sideEffects\": [],\n  \"publishConfig\": {\n    \"access\": \"public\",\n    \"registry\": \"https://registry.npmjs.org/\"\n  }\n}\n",
  "README.md": "# Modern.js Package\n\n## Setup\n\nInstall the dependencies:\n\n```bash\npnpm install\n```\n\n## Get Started\n\nRun and debug the module:\n\n```bash\npnpm dev\n```\n\nRun test cases:\n\n```bash\npnpm test\n```\n\nBuild the module for production:\n\n```bash\npnpm build\n```\n\nEnable optional features:\n\n```bash\npnpm new\n```\n\nOther commands:\n\n```bash\npnpm lint         # Lint and fix source files\npnpm change       # Add a new changeset\npnpm bump         # Update version and changelog via changeset\npnpm release      # Release the package\n```\n\nFor more information, see the [Modern.js Module documentation](https://modernjs.dev/module-tools/en).\n",
  "src/index.ts": "export default function () {\n  return 'hello world';\n}\n",
  "modern.config.ts": "import { moduleTools, defineConfig } from '@modern-js/module-tools';\n\nexport default defineConfig({\n  plugins: [moduleTools()],\n  buildPreset: 'npm-library',\n});\n",
  "tsconfig.json": "{\n  \"extends\": \"@modern-js/tsconfig/base\",\n  \"declaration\": true,\n  \"compilerOptions\": {\n    \"baseUrl\": \"./\",\n    \"paths\": {\n      \"@/*\": [\"./src/*\"]\n    },\n    \"isolatedModules\": true\n  },\n  \"include\": [\"src\"],\n  \"exclude\": [\"**/node_modules\"]\n}\n",
  "src/modern-app-env.d.ts": "/// <reference types='@modern-js/module-tools/types' />\n/// <reference types='@modern-js/plugin-testing/types' />\n"
}
};
