import { commonFiles } from './common';

export const MWAFiles = {
  ...commonFiles,
  ...{
  "README.md": "# Modern.js App\n\n## Setup\n\nInstall the dependencies:\n\n```bash\npnpm install\n```\n\n## Get Started\n\nStart the dev server:\n\n```bash\npnpm dev\n```\n\nEnable optional features or add a new entry:\n\n```bash\npnpm new\n```\n\nBuild the app for production:\n\n```bash\npnpm build\n```\n\nPreview the production build locally:\n\n```bash\npnpm serve\n```\n\nFor more information, see the [Modern.js documentation](https://modernjs.dev/en).\n",
  "package.json": "{\n  \"name\": \"modern-app\",\n  \"version\": \"0.1.0\",\n  \"scripts\": {\n    \"reset\": \"npx rimraf ./**/node_modules\",\n    \"dev\": \"modern dev\",\n    \"build\": \"modern build\",\n    \"start\": \"modern start\",\n    \"serve\": \"modern serve\",\n    \"new\": \"modern new\",\n    \"lint\": \"modern lint\",\n    \"prepare\": \"husky install\",\n    \"upgrade\": \"modern upgrade\"\n  },\n  \"engines\": {\n    \"node\": \">=16.18.1\"\n  },\n  \"lint-staged\": {\n    \"*.{js,jsx,ts,tsx,mjs,cjs}\": [\n      \"node --max_old_space_size=8192 ./node_modules/eslint/bin/eslint.js --fix --color --cache --quiet\"\n    ]\n  },\n  \"eslintIgnore\": [\n    \"node_modules/\",\n    \"dist/\"\n  ],\n  \"dependencies\": {\n    \"@modern-js/runtime\": \"3.0.2\",\n    \"react\": \"~18.2.0\",\n    \"react-dom\": \"~18.2.0\"\n  },\n  \"devDependencies\": {\n    \"@modern-js/app-tools\": \"3.0.2\",\n    \"@modern-js/eslint-config\": \"3.0.2\",\n    \"@modern-js/tsconfig\":\"3.0.2\",\n    \"@modern-js-app/eslint-config\": \"3.0.2\",\n    \"@typescript/native-preview\": \"7.0.0-dev.20260516.1\",\n    \"@types/jest\": \"~29.2.4\",\n    \"@types/node\": \"~16.11.7\",\n    \"@types/react\": \"~18.0.26\",\n    \"@types/react-dom\": \"~18.0.10\",\n    \"lint-staged\": \"~13.1.0\",\n    \"prettier\": \"~2.8.1\",\n    \"husky\": \"~8.0.1\",\n    \"rimraf\": \"~3.0.2\"\n  }\n}\n",
  ".browserslistrc": "chrome >= 51\nedge >= 15\nfirefox >= 54\nsafari >= 10\nios_saf >= 10\n",
  "modern.config.ts": "import { appTools, defineConfig } from '@modern-js/app-tools';\n\n// https://modernjs.dev/en/configure/app/usage\nexport default defineConfig({\n  runtime: {\n    router: true,\n  },\n  plugins: [appTools()],\n});\n",
  "tsconfig.json": "{\n  \"extends\": \"@modern-js/tsconfig/base\",\n  \"compilerOptions\": {\n    \"declaration\": false,\n    \"jsx\": \"preserve\",\n    \"baseUrl\": \"./\",\n    \"paths\": {\n      \"@/*\": [\"./src/*\"],\n      \"@shared/*\": [\"./shared/*\"]\n    }\n  },\n  \"include\": [\"src\", \"shared\", \"config\", \"modern.config.ts\"],\n  \"exclude\": [\"**/node_modules\"]\n}\n",
  "src/modern-app-env.d.ts": "/// <reference types='@modern-js/app-tools/types' />\n/// <reference types='@modern-js/runtime/types' />\n/// <reference types='@modern-js/runtime/types/router' />\n",
  "src/routes/index.css": "html,\nbody {\n  padding: 0;\n  margin: 0;\n  font-family: PingFang SC, Hiragino Sans GB, Microsoft YaHei, Arial, sans-serif;\n  background: linear-gradient(to bottom, transparent, #fff) #eceeef;\n}\n\np {\n  margin: 0;\n}\n\n* {\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n  box-sizing: border-box;\n}\n\n.container-box {\n  min-height: 100vh;\n  max-width: 100%;\n  display: flex;\n  flex-direction: column;\n  justify-content: center;\n  align-items: center;\n  padding-top: 10px;\n}\n\nmain {\n  flex: 1;\n  display: flex;\n  flex-direction: column;\n  justify-content: center;\n  align-items: center;\n}\n\n.title {\n  display: flex;\n  margin: 4rem 0 4rem;\n  align-items: center;\n  font-size: 4rem;\n  font-weight: 600;\n}\n\n.logo {\n  width: 6rem;\n  margin: 7px 0 0 1rem;\n}\n\n.name {\n  color: #4ecaff;\n}\n\n.description {\n  text-align: center;\n  line-height: 1.5;\n  font-size: 1.3rem;\n  color: #1b3a42;\n  margin-bottom: 5rem;\n}\n\n.code {\n  background: #fafafa;\n  border-radius: 12px;\n  padding: 0.6rem 0.9rem;\n  font-size: 1.05rem;\n  font-family: Menlo, Monaco, Lucida Console, Liberation Mono, DejaVu Sans Mono,\n    Bitstream Vera Sans Mono, Courier New, monospace;\n}\n\n.container-box .grid {\n  display: flex;\n  align-items: center;\n  justify-content: center;\n  width: 1100px;\n  margin-top: 3rem;\n}\n\n.card {\n  padding: 1.5rem;\n  display: flex;\n  flex-direction: column;\n  justify-content: center;\n  height: 100px;\n  color: inherit;\n  text-decoration: none;\n  transition: 0.15s ease;\n  width: 45%;\n}\n\n.card:hover,\n.card:focus {\n  transform: scale(1.05);\n}\n\n.card h2 {\n  display: flex;\n  align-items: center;\n  font-size: 1.5rem;\n  margin: 0;\n  padding: 0;\n}\n\n.card p {\n  opacity: 0.6;\n  font-size: 0.9rem;\n  line-height: 1.5;\n  margin-top: 1rem;\n}\n\n.arrow-right {\n  width: 1.3rem;\n  margin-left: 0.5rem;\n  margin-top: 3px;\n}\n",
  "src/routes/page.tsx": "import { Helmet } from '@modern-js/runtime/head';\nimport './index.css';\n\nconst Index = () => (\n  <div className=\"container-box\">\n    <Helmet>\n      <link\n        rel=\"icon\"\n        type=\"image/x-icon\"\n        href=\"https://lf3-static.bytednsdoc.com/obj/eden-cn/uhbfnupenuhf/favicon.ico\"\n      />\n    </Helmet>\n    <main>\n      <div className=\"title\">\n        Welcome to\n        <img\n          className=\"logo\"\n          src=\"https://lf3-static.bytednsdoc.com/obj/eden-cn/zq-uylkvT/ljhwZthlaukjlkulzlp/modern-js-logo.svg\"\n          alt=\"Modern.js Logo\"\n        />\n        <p className=\"name\">Modern.js</p>\n      </div>\n      <p className=\"description\">\n        Get started by editing <code className=\"code\">src/routes/page.tsx</code>\n      </p>\n      <div className=\"grid\">\n        <a\n          href=\"https://modernjs.dev/guides/get-started/introduction.html\"\n          target=\"_blank\"\n          rel=\"noopener noreferrer\"\n          className=\"card\"\n        >\n          <h2>\n            Guide\n            <img\n              className=\"arrow-right\"\n              src=\"https://lf3-static.bytednsdoc.com/obj/eden-cn/zq-uylkvT/ljhwZthlaukjlkulzlp/arrow-right.svg\"\n            />\n          </h2>\n          <p>Follow the guides to use all features of Modern.js.</p>\n        </a>\n        <a\n          href=\"https://modernjs.dev/tutorials/foundations/introduction.html\"\n          target=\"_blank\"\n          className=\"card\"\n          rel=\"noreferrer\"\n        >\n          <h2>\n            Tutorials\n            <img\n              className=\"arrow-right\"\n              src=\"https://lf3-static.bytednsdoc.com/obj/eden-cn/zq-uylkvT/ljhwZthlaukjlkulzlp/arrow-right.svg\"\n            />\n          </h2>\n          <p>Learn to use Modern.js to create your first application.</p>\n        </a>\n        <a\n          href=\"https://modernjs.dev/configure/app/usage.html\"\n          target=\"_blank\"\n          className=\"card\"\n          rel=\"noreferrer\"\n        >\n          <h2>\n            Config\n            <img\n              className=\"arrow-right\"\n              src=\"https://lf3-static.bytednsdoc.com/obj/eden-cn/zq-uylkvT/ljhwZthlaukjlkulzlp/arrow-right.svg\"\n            />\n          </h2>\n          <p>Find all configuration options provided by Modern.js.</p>\n        </a>\n        <a\n          href=\"https://github.com/web-infra-dev/modern.js\"\n          target=\"_blank\"\n          rel=\"noopener noreferrer\"\n          className=\"card\"\n        >\n          <h2>\n            Github\n            <img\n              className=\"arrow-right\"\n              src=\"https://lf3-static.bytednsdoc.com/obj/eden-cn/zq-uylkvT/ljhwZthlaukjlkulzlp/arrow-right.svg\"\n            />\n          </h2>\n          <p>View the source code of Github, feel free to contribute.</p>\n        </a>\n      </div>\n    </main>\n  </div>\n);\n\nexport default Index;\n",
  "src/routes/layout.tsx": "import { Outlet } from '@modern-js/runtime/router';\n\nexport default function Layout() {\n  return (\n    <div>\n      <Outlet />\n    </div>\n  );\n}\n"
}
};
