// This file is auto-generated by Modern.js. Do not edit manually.

import {
  createMemoryHistory,
  createRootRouteWithContext,
  createRoute,
  createRouter,
  createRouteStaticData,
  type ModernRouterContext,
  modernLoaderToTanstack,
  modernTanstackRouterFastDefaults,
} from '@modern-js/plugin-tanstack/runtime';

import component_0 from "../../routes/page";
import { loader as loader_0, action as action_0 } from "../../routes/mf/page.data";
import component_1 from "../../routes/mf/page";
import { loader as loader_1 } from "../../routes/mf-not-found/page.data";
import component_2 from "../../routes/mf-not-found/page";
import { loader as loader_2 } from "../../routes/mf-redirect/page.data";
import component_3 from "../../routes/mf-redirect/page";
import loader_3 from "../../routes/layout.loader";
import component_4 from "../../routes/layout";

export const rootRoute = createRootRouteWithContext<ModernRouterContext>()({
  component: component_4,
  loader: modernLoaderToTanstack({ hasSplat: false }, loader_3),
  staticData: createRouteStaticData({
    modernRouteId: "layout",
    modernRouteLoader: loader_3,
  }),

});

const route_page = createRoute({
  getParentRoute: () => rootRoute,
  path: "/",
  component: component_0,
  staticData: createRouteStaticData({
    modernRouteId: "page",
  }),
});

const route_mf_page = createRoute({
  getParentRoute: () => rootRoute,
  path: "mf",
  component: component_1,
  loader: modernLoaderToTanstack({ hasSplat: false }, loader_0),
  staticData: createRouteStaticData({
    modernRouteId: "mf/page",
    modernRouteLoader: loader_0,
    modernRouteAction: action_0,
  }),
});

const route_mfNotFound_page = createRoute({
  getParentRoute: () => rootRoute,
  path: "mf-not-found",
  component: component_2,
  loader: modernLoaderToTanstack({ hasSplat: false }, loader_1),
  staticData: createRouteStaticData({
    modernRouteId: "mf-not-found/page",
    modernRouteLoader: loader_1,
  }),
});

const route_mfRedirect_page = createRoute({
  getParentRoute: () => rootRoute,
  path: "mf-redirect",
  component: component_3,
  loader: modernLoaderToTanstack({ hasSplat: false }, loader_2),
  staticData: createRouteStaticData({
    modernRouteId: "mf-redirect/page",
    modernRouteLoader: loader_2,
  }),
});

export const routeTree = rootRoute.addChildren([route_page, route_mf_page, route_mfNotFound_page, route_mfRedirect_page]);

export const router = createRouter({
  ...modernTanstackRouterFastDefaults,
  routeTree,
  history: createMemoryHistory({
    initialEntries: ['/'],
  }),
  context: {},
});
