import { spawnSync } from 'node:child_process';
import fs from 'node:fs';
import { createRequire } from 'node:module';
import os from 'node:os';
import path from 'node:path';
import { createRsbuild, type Rspack } from '@rsbuild/core';
import { applyNativeSvgComponents } from '../../src/native-composition/svg-components';

const packageDirectory = path.resolve(__dirname, '../..');
const requireFromPackage = createRequire(
  path.join(packageDirectory, 'package.json'),
);
const { parseSvgDocument } = requireFromPackage(
  './src/native-composition/svg-component-source.cjs',
);
const loaders = {
  solid: path.join(
    packageDirectory,
    'src/renderers/solid/compiler/svg-component-loader.cjs',
  ),
  octane: path.join(
    packageDirectory,
    'src/renderers/octane/compiler/svg-component-loader.cjs',
  ),
} as const;

const badge = `<?xml version="1.0" encoding="UTF-8"?>
<!-- exported -->
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"
  viewBox='0 0 24 24' stroke-width=2 data-label="a &amp; b &#x3C;c&#62;" hidden>
  <title>{Badge}</title>
  <use xlink:href="#g"/>
</svg>
`;

function temporaryDirectory(prefix: string) {
  return fs.mkdtempSync(
    path.join(process.env.OWNED_TEMP_DIR ?? os.tmpdir(), prefix),
  );
}

function runLoader(renderer: keyof typeof loaders, outputDirectory: string) {
  const loader = requireFromPackage(loaders[renderer]);
  let cacheable: boolean | undefined;
  const result: string = loader.call(
    {
      resourcePath: '/app/src/assets/badge icon.svg',
      rootContext: '/app',
      cacheable: (value: boolean) => {
        cacheable = value;
      },
      getOptions: () => ({ outputDirectory }),
    },
    badge,
  );
  return { result, cacheable };
}

describe('SVG component source', () => {
  it('splits root attributes from verbatim inner markup', () => {
    expect(parseSvgDocument(badge, 'badge.svg')).toEqual({
      attributes: {
        viewBox: '0 0 24 24',
        'stroke-width': '2',
        'data-label': 'a & b <c>',
        hidden: '',
      },
      markup: '<title>{Badge}</title>\n  <use xlink:href="#g"/>',
    });
    expect(
      parseSvgDocument('<svg width="1"/>\n<!-- done -->', 'empty.svg'),
    ).toEqual({ attributes: { width: '1' }, markup: '' });
  });

  it('rejects documents without one SVG root', () => {
    expect(() => parseSvgDocument('<div></div>', 'a.svg')).toThrow(
      'a.svg must contain one <svg> root element',
    );
    expect(() => parseSvgDocument('<svg><g>', 'b.svg')).toThrow(
      'b.svg has no closing </svg> tag',
    );
    expect(() => parseSvgDocument('<svg></svg><p/>', 'd.svg')).toThrow(
      'd.svg has content after its <svg> root element',
    );
  });

  it.each([
    ['solid', 'innerHTML={markup}', "from '@solidjs/web'"],
    ['octane', 'dangerouslySetInnerHTML={markup}', "from 'octane'"],
  ] as const)('emits a %s component module the renderer compiles', (renderer, children, runtime) => {
    const outputDirectory = temporaryDirectory('um-svg-component-');
    try {
      const first = runLoader(renderer, outputDirectory);
      expect(first.cacheable).toBe(false);
      const [file] = fs.readdirSync(outputDirectory);
      expect(file).toMatch(/^badge_icon-[\da-f]{16}\.tsx$/u);
      const generated = path.join(outputDirectory, file);
      expect(first.result).toBe(
        `export { default } from ${JSON.stringify(generated)};\n`,
      );
      const source = fs.readFileSync(generated, 'utf8');
      expect(source).toContain(children);
      expect(source).toContain(runtime);
      expect(source).toContain(
        'Generated by UltraModern from src/assets/badge icon.svg',
      );
      expect(source).toContain('"data-label": "a & b <c>"');
      expect(source).not.toContain('xmlns');
      // Unchanged sources keep the generated file untouched for watchers.
      const modified = fs.statSync(generated).mtimeMs;
      runLoader(renderer, outputDirectory);
      expect(fs.statSync(generated).mtimeMs).toBe(modified);
      expect(fs.readdirSync(outputDirectory)).toEqual([file]);
    } finally {
      fs.rmSync(outputDirectory, { recursive: true, force: true });
    }
  });
});

describe('SVG component rules', () => {
  async function svgRule(defaultExport?: 'component' | 'url') {
    const root = temporaryDirectory('um-svg-rule-');
    try {
      const rsbuild = await createRsbuild({
        cwd: root,
        rsbuildConfig: {
          source: { entry: { main: path.join(root, 'index.ts') } },
          html: { htmlPlugin: false },
          plugins: [
            {
              name: 'fixture:svg-components',
              setup(api) {
                applyNativeSvgComponents(api, {
                  renderer: 'solid',
                  loader: loaders.solid,
                  defaultExport,
                });
              },
            },
          ],
        },
      });
      const [config] = await rsbuild.initConfigs();
      const rule = config.module!.rules!.find(
        candidate =>
          candidate &&
          typeof candidate === 'object' &&
          candidate.test instanceof RegExp &&
          candidate.test.test('icon.svg') &&
          Array.isArray(candidate.oneOf),
      ) as Rspack.RuleSetRule;
      return { root, oneOf: rule.oneOf as Rspack.RuleSetRule[] };
    } finally {
      fs.rmSync(root, { recursive: true, force: true });
    }
  }

  it('routes ?component imports before every URL asset query', async () => {
    const { root, oneOf } = await svgRule();
    expect(oneOf[0].resourceQuery).toEqual(/^\?component$/u);
    expect(oneOf[0].type).toBe('javascript/auto');
    expect(oneOf[0].use).toEqual([
      {
        loader: loaders.solid,
        options: {
          outputDirectory: path.join(
            root,
            'node_modules/.modern-js/solid/svg-components',
          ),
        },
      },
    ]);
    // URL imports remain the default export.
    expect(oneOf.at(-1)?.type).toBe('asset');
    expect(oneOf.filter(rule => rule.issuer)).toEqual([]);
  });

  it('makes script default imports components only when configured', async () => {
    const { oneOf } = await svgRule('component');
    const defaultComponent = oneOf.at(-2)!;
    expect(defaultComponent.issuer).toEqual(/\.(?:[cm]?[jt]sx?|tsrx)$/u);
    expect(defaultComponent.resourceQuery).toBeUndefined();
    expect(oneOf.at(-1)?.type).toBe('asset');
    expect(
      oneOf.findIndex(rule => rule.type === 'asset/resource'),
    ).toBeLessThan(oneOf.indexOf(defaultComponent));
  });
});

describe('SVG component types', () => {
  const typescript = requireFromPackage.resolve('typescript/package.json');
  const tsc = path.resolve(
    path.dirname(typescript),
    JSON.parse(fs.readFileSync(typescript, 'utf8')).bin.tsc,
  );
  const solidWeb = fs.realpathSync(
    path.join(
      packageDirectory,
      'node_modules/@modern-js/renderer-solid/node_modules/@solidjs/web',
    ),
  );
  const octane = fs.realpathSync(
    path.join(packageDirectory, 'node_modules/octane'),
  );
  const rsbuild = fs.realpathSync(
    path.join(packageDirectory, 'node_modules/@rsbuild/core'),
  );

  it.each([
    [
      'solid',
      '@solidjs/web',
      { '@solidjs/web': solidWeb },
      'import type { JSX } from \'@solidjs/web\';\nexport const view = (): JSX.Element => <Badge class="icon" width={24} ref={(element: SVGSVGElement) => element} />;\n',
    ],
    [
      'octane',
      'octane',
      { octane },
      'export const view = () => <Badge class="icon" width={24} ref={(element: SVGSVGElement | null) => element} />;\n',
    ],
  ] as const)('type-checks generated %s modules and ?component imports', (renderer, jsxImportSource, packages, usage) => {
    const directory = temporaryDirectory('um-svg-types-');
    try {
      const modules = path.join(directory, 'node_modules');
      fs.mkdirSync(path.join(modules, '@modern-js'), { recursive: true });
      fs.mkdirSync(path.join(modules, '@solidjs'), { recursive: true });
      fs.symlinkSync(
        packageDirectory,
        path.join(modules, '@modern-js/ultramodern-app-tools'),
        'dir',
      );
      fs.mkdirSync(path.join(modules, '@rsbuild'), { recursive: true });
      fs.symlinkSync(rsbuild, path.join(modules, '@rsbuild/core'), 'dir');
      for (const [name, target] of Object.entries(packages))
        fs.symlinkSync(target, path.join(modules, name), 'dir');
      const outputDirectory = path.join(
        modules,
        '.modern-js',
        renderer,
        'svg-components',
      );
      runLoader(renderer, outputDirectory);
      fs.writeFileSync(
        path.join(directory, 'app.tsx'),
        `/// <reference types="@modern-js/ultramodern-app-tools/types" />\nimport Badge from './badge.svg?component';\n${usage}`,
      );
      fs.writeFileSync(
        path.join(directory, 'tsconfig.json'),
        JSON.stringify({
          compilerOptions: {
            target: 'ESNext',
            module: 'ESNext',
            moduleResolution: 'Bundler',
            jsx: 'preserve',
            jsxImportSource,
            strict: true,
            noEmit: true,
            skipLibCheck: true,
            types: [],
          },
          include: ['app.tsx', 'node_modules/.modern-js'],
        }),
      );
      const result = spawnSync(
        process.execPath,
        [tsc, '-p', path.join(directory, 'tsconfig.json')],
        { cwd: directory, encoding: 'utf8', timeout: 60_000 },
      );
      expect(
        result.status,
        `${result.stdout ?? ''}${result.stderr ?? ''}`,
      ).toBe(0);
    } finally {
      fs.rmSync(directory, { recursive: true, force: true });
    }
  });
});
