#!/usr/bin/env node
import assert from 'node:assert/strict';
import { createHash } from 'node:crypto';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import inventory from '../../packages/toolkit/ultramodern-create/src/ultramodern-workspace/patch-inventory.ts';

const root = fileURLToPath(new URL('../../', import.meta.url));
const generator = path.join(root, 'packages/toolkit/ultramodern-create');
const write = process.argv.includes('--write');
const assetsOnly = process.argv.includes('--write-assets');
const expected = new Set();
const selectors = new Set();
for (const patch of inventory) {
  assert.match(patch.path, /^patches\/[^/]+\.patch$/u);
  assert.ok(
    !selectors.has(`${patch.packageName}@${patch.version}`),
    'duplicate patch selector',
  );
  selectors.add(`${patch.packageName}@${patch.version}`);
  assert.ok([null, 'required', 'conditional'].includes(patch.workspace));
  const bytes = fs.readFileSync(path.join(root, patch.path));
  assert.equal(
    createHash('sha256').update(bytes).digest('hex'),
    patch.sha256,
    `patch integrity: ${patch.path}`,
  );
  if (patch.workspace !== null) {
    expected.add(path.basename(patch.path));
    const target = path.join(generator, 'template-workspace', patch.path);
    if (write || assetsOnly) fs.writeFileSync(target, bytes);
    assert.deepEqual(
      fs.readFileSync(target),
      bytes,
      `stale packaged patch: ${target}`,
    );
  }
}
assert.deepEqual(
  new Set(
    fs.existsSync(path.join(generator, 'template-workspace/patches'))
      ? fs.readdirSync(path.join(generator, 'template-workspace/patches'))
      : [],
  ),
  expected,
  'unexpected/missing packaged patches',
);
const block = `patchedDependencies:\n${inventory
  .filter(p => p.repository)
  .map(p => `  '${p.packageName}@${p.version}': ${p.path}`)
  .join('\n')}\n`;
const workspace = path.join(root, 'pnpm-workspace.yaml');
const yaml = fs.readFileSync(workspace, 'utf8');
const match = yaml.match(/^patchedDependencies:\n(?:[ \t].*\n|\n)*/mu);
assert.ok(match, 'repository patchedDependencies section is required');
if (write) fs.writeFileSync(workspace, yaml.replace(match[0], block));
if (!assetsOnly)
  assert.equal(
    write ? block : match[0],
    block,
    'root patch configuration differs; run sync-patches.mjs --write',
  );
const readme = `# Patch inventory\n\nGenerated by \`node scripts/ultramodern-supply/sync-patches.mjs --write\`.\nEdit \`packages/toolkit/ultramodern-create/src/ultramodern-workspace/patch-inventory.ts\` and the canonical bytes under \`patches/\`; this ledger and root configuration are derived. Corrected third-party artifacts are published by the sidecar producer. Each inventory entry pins the patch SHA-256, exact dependency version and applicability. Generated workspaces carry no framework patches.\n\n| Package | Repository | Workspace | Purpose |\n| --- | --- | --- | --- |\n${inventory.map(p => `| ${p.packageName}@${p.version} | ${p.repository ? 'yes' : 'no'} | ${p.workspace ?? 'none'} | ${p.reason} |`).join('\n')}\n\nRun the command without flags to verify integrity and all projections. \`--write-assets\` updates only packaged assets and this document; \`--write\` also regenerates the repository configuration. Regenerate the lockfile with pnpm when patch bytes or dependency selectors change. Never hand-edit packaged copies.\n\nPatch retirement requires proving the upstream replacement preserves its behavior. Application shims are not a replacement. Image parser hardening is also used by the pinned [sidecar recipe](../scripts/ultramodern-supply/README.md).\n`;
const documentation = path.join(root, 'patches/README.md');
if (write || assetsOnly) fs.writeFileSync(documentation, readme);
else
  assert.equal(
    fs.readFileSync(documentation, 'utf8'),
    readme,
    'patch ledger is stale',
  );
console.log(
  `Verified ${inventory.length} canonical patches and ${expected.size} packaged assets.`,
);
