// This file is auto-generated by Modern.js. Do not edit manually.

import {
  createMemoryHistory,
  createRootRouteWithContext,
  createRoute,
  createRouter,
  createRouteStaticData,
  type ModernRouterContext,
  modernLoaderToTanstack,
  modernTanstackRouterFastDefaults,
} from '@modern-js/plugin-tanstack/runtime';

import { loader as loader_0 } from "../../stream/routes/page.data";
import component_0 from "../../stream/routes/page";
import { loader as loader_1 } from "../../stream/routes/optional/[id$]/page.data";
import component_1 from "../../stream/routes/optional/[id$]/page";
import { loader as loader_2 } from "../../stream/routes/redirect/page.data";
import component_2 from "../../stream/routes/redirect/page";
import { loader as loader_3 } from "../../stream/routes/user/[id]/page.data";
import component_3 from "../../stream/routes/user/[id]/page";
import loader_4 from "../../stream/routes/layout.loader";
import component_4 from "../../stream/routes/layout";

export const rootRoute = createRootRouteWithContext<ModernRouterContext>()({
  component: component_4,
  loader: modernLoaderToTanstack({ hasSplat: false }, loader_4),
  staticData: createRouteStaticData({
    modernRouteId: "stream_layout",
    modernRouteLoader: loader_4,
  }),

});

const route_stream_page = createRoute({
  getParentRoute: () => rootRoute,
  path: "/",
  component: component_0,
  loader: modernLoaderToTanstack({ hasSplat: false }, loader_0),
  staticData: createRouteStaticData({
    modernRouteId: "stream_page",
    modernRouteLoader: loader_0,
  }),
});

const route_stream_optional__id$__page = createRoute({
  getParentRoute: () => rootRoute,
  path: "optional/{-$id}",
  component: component_1,
  loader: modernLoaderToTanstack({ hasSplat: false }, loader_1),
  staticData: createRouteStaticData({
    modernRouteId: "stream_optional/(id$)/page",
    modernRouteLoader: loader_1,
  }),
});

const route_stream_redirect_page = createRoute({
  getParentRoute: () => rootRoute,
  path: "redirect",
  component: component_2,
  loader: modernLoaderToTanstack({ hasSplat: false }, loader_2),
  staticData: createRouteStaticData({
    modernRouteId: "stream_redirect/page",
    modernRouteLoader: loader_2,
  }),
});

const route_stream_user__id__page = createRoute({
  getParentRoute: () => rootRoute,
  path: "user/$id",
  component: component_3,
  loader: modernLoaderToTanstack({ hasSplat: false }, loader_3),
  staticData: createRouteStaticData({
    modernRouteId: "stream_user/(id)/page",
    modernRouteLoader: loader_3,
  }),
});

export const routeTree = rootRoute.addChildren([route_stream_page, route_stream_optional__id$__page, route_stream_redirect_page, route_stream_user__id__page]);

export const router = createRouter({
  ...modernTanstackRouterFastDefaults,
  routeTree,
  history: createMemoryHistory({
    initialEntries: ['/'],
  }),
  context: {},
});
