import { spawnSync } from 'node:child_process';
import { mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { createRequire } from 'node:module';
import path from 'node:path';

const requireCjs = createRequire(import.meta.url);

// The `createLazyComponent` signature of `@module-federation/bridge-react`.
const MODULE_FEDERATION_BRIDGE = `
import type { ComponentType, ReactNode } from 'react';

export type CreateLazyComponentOptions<T, E extends keyof T> = {
  loader: () => Promise<T>;
  instance: unknown;
  loading: ReactNode;
  fallback: ReactNode;
  export?: E;
  injectLink?: boolean;
};
export declare function createLazyComponent<T, E extends keyof T>(
  options: CreateLazyComponentOptions<T, E>,
): T[E] extends ComponentType<infer Props> ? ComponentType<Props> : never;
export declare function getInstance(): unknown;
`;

const CONSUMER = `
import type { FunctionComponent, ReactNode } from 'react';
import { createDistributedSsrComponent } from '../../../src/module-federation/distributed-ssr';
import { createLazyComponent, getInstance } from './bridge';

type AddToCartProps = { sku: string };
interface RemoteComponentModule<Props extends object> {
  default: FunctionComponent<Props>;
}
declare const loadAddToCart: () => Promise<RemoteComponentModule<AddToCartProps>>;

export const createFederatedComponents = (fallback: ReactNode) => ({
  // Shells generated by earlier releases (the Tractor demo) build the native
  // remote in a factory that takes no options.
  Published: createDistributedSsrComponent<AddToCartProps>({
    createComponent: () =>
      createLazyComponent<RemoteComponentModule<AddToCartProps>, 'default'>({
        export: 'default',
        fallback,
        instance: getInstance(),
        loader: loadAddToCart,
        loading: null,
      }),
    expose: './AddToCart',
    fallback,
    remote: 'checkout',
  }),
  // Current shells spread the options the boundary owns.
  Generated: createDistributedSsrComponent<AddToCartProps>({
    createComponent: options =>
      createLazyComponent<RemoteComponentModule<AddToCartProps>, 'default'>({
        ...options,
        instance: getInstance(),
        loader: loadAddToCart,
      }),
    expose: './AddToCart',
    fallback,
    remote: 'checkout',
  }),
});
`;

describe('createDistributedSsrComponent types', () => {
  it('type-checks published and generated shells', () => {
    const fixtureRoot = mkdtempSync(path.join(__dirname, '.types-'));
    try {
      writeFileSync(
        path.join(fixtureRoot, 'bridge.ts'),
        MODULE_FEDERATION_BRIDGE,
      );
      writeFileSync(path.join(fixtureRoot, 'shell.tsx'), CONSUMER);
      writeFileSync(
        path.join(fixtureRoot, 'tsconfig.json'),
        JSON.stringify({
          compilerOptions: {
            jsx: 'react-jsx',
            lib: ['DOM', 'ESNext'],
            module: 'ESNext',
            moduleResolution: 'Bundler',
            noEmit: true,
            skipLibCheck: true,
            strict: true,
            target: 'ES2024',
            types: [],
          },
          include: ['shell.tsx'],
        }),
      );
      const compilerManifestPath = requireCjs.resolve(
        '@typescript/native-preview/package.json',
      );
      const { bin } = JSON.parse(
        readFileSync(compilerManifestPath, 'utf8'),
      ) as { bin: { tsgo: string } };
      const result = spawnSync(
        process.execPath,
        [
          path.resolve(path.dirname(compilerManifestPath), bin.tsgo),
          '--project',
          path.join(fixtureRoot, 'tsconfig.json'),
        ],
        { encoding: 'utf8' },
      );

      expect(result.error).toBeUndefined();
      expect(result.status, `${result.stdout}\n${result.stderr}`).toBe(0);
    } finally {
      rmSync(fixtureRoot, { force: true, recursive: true });
    }
  });
});
