import './register';

export type * from '@tanstack/react-router';
export {
  Asset,
  Await,
  Block,
  CatchBoundary,
  CatchNotFound,
  ClientOnly,
  cleanPath,
  composeRewrites,
  createBrowserHistory,
  createControlledPromise,
  createFileRoute,
  createHashHistory,
  createHistory,
  createLazyFileRoute,
  createLazyRoute,
  createLink,
  createMemoryHistory,
  createRootRoute,
  createRootRouteWithContext,
  createRoute,
  createRouteMask,
  createRouter,
  createRouterConfig,
  createSerializationAdapter,
  DEFAULT_PROTOCOL_ALLOWLIST,
  DefaultGlobalNotFound,
  deepEqual,
  defaultParseSearch,
  defaultStringifySearch,
  defer,
  ErrorComponent,
  FileRoute,
  FileRouteLoader,
  functionalUpdate,
  getRouteApi,
  HeadContent,
  interpolatePath,
  isMatch,
  isNotFound,
  isPlainArray,
  isPlainObject,
  isRedirect,
  joinPaths,
  LazyRoute,
  lazyFn,
  lazyRouteComponent,
  linkOptions,
  Match,
  Matches,
  MatchRoute,
  Navigate,
  NotFoundRoute,
  notFound,
  parseSearchWith,
  RootRoute,
  Route,
  RouteApi,
  Router,
  RouterContextProvider,
  RouterProvider,
  reactUse,
  redirect,
  replaceEqualDeep,
  resolvePath,
  retainSearchParams,
  rootRouteId,
  rootRouteWithContext,
  ScriptOnce,
  Scripts,
  ScrollRestoration,
  SearchParamError,
  stringifySearchWith,
  stripSearchParams,
  trimPath,
  trimPathLeft,
  trimPathRight,
  useAwaited,
  useBlocker,
  useCanGoBack,
  useChildMatches,
  useElementScrollRestoration,
  useHydrated,
  useLayoutEffect,
  useLinkProps,
  useLoaderData,
  useLoaderDeps,
  useLocation,
  useMatch,
  useMatches,
  useMatchRoute,
  useNavigate,
  useParams,
  useParentMatches,
  useRouteContext,
  useRouter,
  useRouterState,
  useSearch,
  useTags,
} from '@tanstack/react-router';
export type {
  Fetcher,
  FetcherState,
  FetcherSubmitOptions,
  FormProps,
  SubmitOptions,
} from './dataMutation';
export {
  Form,
  RouteActionResponseError,
  useFetcher,
} from './dataMutation';
export type { ModernRouterContext } from './loaderBridge';
export {
  createRouteStaticData,
  isAbsoluteUrl,
  modernLoaderToTanstack,
  throwTanstackRedirect,
} from './loaderBridge';
export { Outlet } from './outlet';
export {
  tanstackRouterPlugin,
  tanstackRouterPlugin as default,
} from './plugin';
export type {
  LinkProps,
  NavLinkProps,
  PrefetchBehavior,
} from './prefetchLink';
export { Link, NavLink } from './prefetchLink';
export type {
  AnyCompositeComponent,
  AnyRenderableServerComponent,
  CompositeComponentProps,
} from './rsc/client';
export { CompositeComponent } from './rsc/client';
export type { TanstackRouterState } from './state';
export { getTanstackRouterState } from './state';
export type { RouterConfig } from './types';
export {
  getModernTanstackRouterFastDefaults,
  modernTanstackRouterFastDefaults,
} from './types';
