packages:
  - apps/*
  - apps/remotes/*
  - services/*
  - packages/*

allowBuilds:
  '@swc/core': true
  core-js: true
  esbuild: true
  msgpackr-extract: true

onlyBuiltDependencies:
  - '@swc/core'
  - core-js
  - esbuild
  - msgpackr-extract
