packages:
  - apps/*
  - apps/remotes/*
  - services/*
  - packages/*

allowBuilds:
  '@biomejs/biome': true
  '@swc/core': true
  core-js: true
  esbuild: true
  msgpackr-extract: true

onlyBuiltDependencies:
  - '@biomejs/biome'
  - '@swc/core'
  - core-js
  - esbuild
  - msgpackr-extract
